// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: trading/exchange.proto

package trading

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Exchange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Acronym        string                 `protobuf:"bytes,3,opt,name=acronym,proto3" json:"acronym,omitempty"`
	MicCode        string                 `protobuf:"bytes,4,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	Polity         string                 `protobuf:"bytes,5,opt,name=polity,proto3" json:"polity,omitempty"`
	Currency       string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	TimeZoneOffset string                 `protobuf:"bytes,7,opt,name=time_zone_offset,json=timeZoneOffset,proto3" json:"time_zone_offset,omitempty"`
	OpenOverride   bool                   `protobuf:"varint,8,opt,name=open_override,json=openOverride,proto3" json:"open_override,omitempty"`
	// Local-time working hours as "HH:MM:SS" (Postgres TIME). Clients that only
	// care about HH:MM can truncate.
	OpenTime      string `protobuf:"bytes,9,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     string `protobuf:"bytes,10,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exchange) Reset() {
	*x = Exchange{}
	mi := &file_trading_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange) ProtoMessage() {}

func (x *Exchange) ProtoReflect() protoreflect.Message {
	mi := &file_trading_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange.ProtoReflect.Descriptor instead.
func (*Exchange) Descriptor() ([]byte, []int) {
	return file_trading_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *Exchange) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Exchange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exchange) GetAcronym() string {
	if x != nil {
		return x.Acronym
	}
	return ""
}

func (x *Exchange) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

func (x *Exchange) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *Exchange) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Exchange) GetTimeZoneOffset() string {
	if x != nil {
		return x.TimeZoneOffset
	}
	return ""
}

func (x *Exchange) GetOpenOverride() bool {
	if x != nil {
		return x.OpenOverride
	}
	return false
}

func (x *Exchange) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *Exchange) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

type ListExchangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExchangesRequest) Reset() {
	*x = ListExchangesRequest{}
	mi := &file_trading_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExchangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExchangesRequest) ProtoMessage() {}

func (x *ListExchangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExchangesRequest.ProtoReflect.Descriptor instead.
func (*ListExchangesRequest) Descriptor() ([]byte, []int) {
	return file_trading_exchange_proto_rawDescGZIP(), []int{1}
}

type ListExchangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchanges     []*Exchange            `protobuf:"bytes,1,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExchangesResponse) Reset() {
	*x = ListExchangesResponse{}
	mi := &file_trading_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExchangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExchangesResponse) ProtoMessage() {}

func (x *ListExchangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExchangesResponse.ProtoReflect.Descriptor instead.
func (*ListExchangesResponse) Descriptor() ([]byte, []int) {
	return file_trading_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *ListExchangesResponse) GetExchanges() []*Exchange {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

// Supervisor-only (gated at the gateway by `secured("supervisor")`; the
// trading server re-checks against employee_permissions). Flips the
// exchange's open_override flag — when true, IsOpen returns true regardless
// of the clock, which lets us exercise the trading flow outside real market
// hours.
type SetExchangeOpenOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int64                  `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	OpenOverride  bool                   `protobuf:"varint,2,opt,name=open_override,json=openOverride,proto3" json:"open_override,omitempty"`
	CallerEmail   string                 `protobuf:"bytes,3,opt,name=caller_email,json=callerEmail,proto3" json:"caller_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetExchangeOpenOverrideRequest) Reset() {
	*x = SetExchangeOpenOverrideRequest{}
	mi := &file_trading_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetExchangeOpenOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExchangeOpenOverrideRequest) ProtoMessage() {}

func (x *SetExchangeOpenOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetExchangeOpenOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetExchangeOpenOverrideRequest) Descriptor() ([]byte, []int) {
	return file_trading_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *SetExchangeOpenOverrideRequest) GetExchangeId() int64 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *SetExchangeOpenOverrideRequest) GetOpenOverride() bool {
	if x != nil {
		return x.OpenOverride
	}
	return false
}

func (x *SetExchangeOpenOverrideRequest) GetCallerEmail() string {
	if x != nil {
		return x.CallerEmail
	}
	return ""
}

type SetExchangeOpenOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *Exchange              `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetExchangeOpenOverrideResponse) Reset() {
	*x = SetExchangeOpenOverrideResponse{}
	mi := &file_trading_exchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetExchangeOpenOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExchangeOpenOverrideResponse) ProtoMessage() {}

func (x *SetExchangeOpenOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_exchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetExchangeOpenOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetExchangeOpenOverrideResponse) Descriptor() ([]byte, []int) {
	return file_trading_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *SetExchangeOpenOverrideResponse) GetExchange() *Exchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

var File_trading_exchange_proto protoreflect.FileDescriptor

const file_trading_exchange_proto_rawDesc = "" +
	"\n" +
	"\x16trading/exchange.proto\x12\atrading\"\xa2\x02\n" +
	"\bExchange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aacronym\x18\x03 \x01(\tR\aacronym\x12\x19\n" +
	"\bmic_code\x18\x04 \x01(\tR\amicCode\x12\x16\n" +
	"\x06polity\x18\x05 \x01(\tR\x06polity\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12(\n" +
	"\x10time_zone_offset\x18\a \x01(\tR\x0etimeZoneOffset\x12#\n" +
	"\ropen_override\x18\b \x01(\bR\fopenOverride\x12\x1b\n" +
	"\topen_time\x18\t \x01(\tR\bopenTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\n" +
	" \x01(\tR\tcloseTime\"\x16\n" +
	"\x14ListExchangesRequest\"H\n" +
	"\x15ListExchangesResponse\x12/\n" +
	"\texchanges\x18\x01 \x03(\v2\x11.trading.ExchangeR\texchanges\"\x89\x01\n" +
	"\x1eSetExchangeOpenOverrideRequest\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x03R\n" +
	"exchangeId\x12#\n" +
	"\ropen_override\x18\x02 \x01(\bR\fopenOverride\x12!\n" +
	"\fcaller_email\x18\x03 \x01(\tR\vcallerEmail\"P\n" +
	"\x1fSetExchangeOpenOverrideResponse\x12-\n" +
	"\bexchange\x18\x01 \x01(\v2\x11.trading.ExchangeR\bexchangeB:Z8github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/tradingb\x06proto3"

var (
	file_trading_exchange_proto_rawDescOnce sync.Once
	file_trading_exchange_proto_rawDescData []byte
)

func file_trading_exchange_proto_rawDescGZIP() []byte {
	file_trading_exchange_proto_rawDescOnce.Do(func() {
		file_trading_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_exchange_proto_rawDesc), len(file_trading_exchange_proto_rawDesc)))
	})
	return file_trading_exchange_proto_rawDescData
}

var file_trading_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_trading_exchange_proto_goTypes = []any{
	(*Exchange)(nil),                        // 0: trading.Exchange
	(*ListExchangesRequest)(nil),            // 1: trading.ListExchangesRequest
	(*ListExchangesResponse)(nil),           // 2: trading.ListExchangesResponse
	(*SetExchangeOpenOverrideRequest)(nil),  // 3: trading.SetExchangeOpenOverrideRequest
	(*SetExchangeOpenOverrideResponse)(nil), // 4: trading.SetExchangeOpenOverrideResponse
}
var file_trading_exchange_proto_depIdxs = []int32{
	0, // 0: trading.ListExchangesResponse.exchanges:type_name -> trading.Exchange
	0, // 1: trading.SetExchangeOpenOverrideResponse.exchange:type_name -> trading.Exchange
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trading_exchange_proto_init() }
func file_trading_exchange_proto_init() {
	if File_trading_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_exchange_proto_rawDesc), len(file_trading_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trading_exchange_proto_goTypes,
		DependencyIndexes: file_trading_exchange_proto_depIdxs,
		MessageInfos:      file_trading_exchange_proto_msgTypes,
	}.Build()
	File_trading_exchange_proto = out.File
	file_trading_exchange_proto_goTypes = nil
	file_trading_exchange_proto_depIdxs = nil
}
