// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: trading/holding.proto

package trading

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Holding is one row in the portfolio portal (spec p.62 / #207). Exactly one
// of stock_id / future_id / forex_pair_id / option_id is set — the asset_type
// string ("stock"|"future"|"forex"|"option") gives the UI a single switch.
// avg_cost is denominated in the booking account's currency; current_price
// uses the instrument's quote currency (listing price, option premium, or
// forex_pair.exchange_rate × 100). profit converts the current quote into the
// account's currency before subtracting avg_cost so the displayed P/L lines
// up with what would actually settle on a sell. public_amount is meaningful
// only for stock holdings (OTC counter, fourth celina) and stays 0 elsewhere.
type Holding struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlacerId         int64                  `protobuf:"varint,2,opt,name=placer_id,json=placerId,proto3" json:"placer_id,omitempty"`
	StockId          int64                  `protobuf:"varint,3,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	FutureId         int64                  `protobuf:"varint,4,opt,name=future_id,json=futureId,proto3" json:"future_id,omitempty"`
	ForexPairId      int64                  `protobuf:"varint,5,opt,name=forex_pair_id,json=forexPairId,proto3" json:"forex_pair_id,omitempty"`
	OptionId         int64                  `protobuf:"varint,6,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	Amount           int64                  `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	AvgCost          int64                  `protobuf:"varint,8,opt,name=avg_cost,json=avgCost,proto3" json:"avg_cost,omitempty"`
	AccountId        int64                  `protobuf:"varint,9,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountNumber    string                 `protobuf:"bytes,10,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	PublicAmount     int64                  `protobuf:"varint,11,opt,name=public_amount,json=publicAmount,proto3" json:"public_amount,omitempty"`
	Ticker           string                 `protobuf:"bytes,12,opt,name=ticker,proto3" json:"ticker,omitempty"`
	CurrentPrice     int64                  `protobuf:"varint,13,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Profit           int64                  `protobuf:"varint,14,opt,name=profit,proto3" json:"profit,omitempty"`
	LastModifiedUnix int64                  `protobuf:"varint,15,opt,name=last_modified_unix,json=lastModifiedUnix,proto3" json:"last_modified_unix,omitempty"`
	AssetType        string                 `protobuf:"bytes,16,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Holding) Reset() {
	*x = Holding{}
	mi := &file_trading_holding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holding) ProtoMessage() {}

func (x *Holding) ProtoReflect() protoreflect.Message {
	mi := &file_trading_holding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holding.ProtoReflect.Descriptor instead.
func (*Holding) Descriptor() ([]byte, []int) {
	return file_trading_holding_proto_rawDescGZIP(), []int{0}
}

func (x *Holding) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Holding) GetPlacerId() int64 {
	if x != nil {
		return x.PlacerId
	}
	return 0
}

func (x *Holding) GetStockId() int64 {
	if x != nil {
		return x.StockId
	}
	return 0
}

func (x *Holding) GetFutureId() int64 {
	if x != nil {
		return x.FutureId
	}
	return 0
}

func (x *Holding) GetForexPairId() int64 {
	if x != nil {
		return x.ForexPairId
	}
	return 0
}

func (x *Holding) GetOptionId() int64 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

func (x *Holding) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Holding) GetAvgCost() int64 {
	if x != nil {
		return x.AvgCost
	}
	return 0
}

func (x *Holding) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Holding) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Holding) GetPublicAmount() int64 {
	if x != nil {
		return x.PublicAmount
	}
	return 0
}

func (x *Holding) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Holding) GetCurrentPrice() int64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *Holding) GetProfit() int64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

func (x *Holding) GetLastModifiedUnix() int64 {
	if x != nil {
		return x.LastModifiedUnix
	}
	return 0
}

func (x *Holding) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

type ListHoldingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerEmail   string                 `protobuf:"bytes,1,opt,name=caller_email,json=callerEmail,proto3" json:"caller_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHoldingsRequest) Reset() {
	*x = ListHoldingsRequest{}
	mi := &file_trading_holding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHoldingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHoldingsRequest) ProtoMessage() {}

func (x *ListHoldingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_holding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHoldingsRequest.ProtoReflect.Descriptor instead.
func (*ListHoldingsRequest) Descriptor() ([]byte, []int) {
	return file_trading_holding_proto_rawDescGZIP(), []int{1}
}

func (x *ListHoldingsRequest) GetCallerEmail() string {
	if x != nil {
		return x.CallerEmail
	}
	return ""
}

type ListHoldingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holdings      []*Holding             `protobuf:"bytes,1,rep,name=holdings,proto3" json:"holdings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHoldingsResponse) Reset() {
	*x = ListHoldingsResponse{}
	mi := &file_trading_holding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHoldingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHoldingsResponse) ProtoMessage() {}

func (x *ListHoldingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_holding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHoldingsResponse.ProtoReflect.Descriptor instead.
func (*ListHoldingsResponse) Descriptor() ([]byte, []int) {
	return file_trading_holding_proto_rawDescGZIP(), []int{2}
}

func (x *ListHoldingsResponse) GetHoldings() []*Holding {
	if x != nil {
		return x.Holdings
	}
	return nil
}

// SellHolding is the spec's `POST /api/portfolio/sell` thin wrapper. The
// server resolves the holding to its underlying asset and forwards a
// CreateOrder with direction=sell, so the same execution / approval / margin
// pipeline applies. The caller must own the holding (placer matches) — the
// server enforces this rather than the gateway since the holding row carries
// the authoritative placer link.
type SellHoldingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldingId     int64                  `protobuf:"varint,1,opt,name=holding_id,json=holdingId,proto3" json:"holding_id,omitempty"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	OrderType     string                 `protobuf:"bytes,3,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LimitPrice    int64                  `protobuf:"varint,5,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	StopPrice     int64                  `protobuf:"varint,6,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	AllOrNone     bool                   `protobuf:"varint,7,opt,name=all_or_none,json=allOrNone,proto3" json:"all_or_none,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellHoldingRequest) Reset() {
	*x = SellHoldingRequest{}
	mi := &file_trading_holding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellHoldingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellHoldingRequest) ProtoMessage() {}

func (x *SellHoldingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_holding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellHoldingRequest.ProtoReflect.Descriptor instead.
func (*SellHoldingRequest) Descriptor() ([]byte, []int) {
	return file_trading_holding_proto_rawDescGZIP(), []int{3}
}

func (x *SellHoldingRequest) GetHoldingId() int64 {
	if x != nil {
		return x.HoldingId
	}
	return 0
}

func (x *SellHoldingRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *SellHoldingRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *SellHoldingRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SellHoldingRequest) GetLimitPrice() int64 {
	if x != nil {
		return x.LimitPrice
	}
	return 0
}

func (x *SellHoldingRequest) GetStopPrice() int64 {
	if x != nil {
		return x.StopPrice
	}
	return 0
}

func (x *SellHoldingRequest) GetAllOrNone() bool {
	if x != nil {
		return x.AllOrNone
	}
	return false
}

type SellHoldingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellHoldingResponse) Reset() {
	*x = SellHoldingResponse{}
	mi := &file_trading_holding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellHoldingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellHoldingResponse) ProtoMessage() {}

func (x *SellHoldingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_holding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellHoldingResponse.ProtoReflect.Descriptor instead.
func (*SellHoldingResponse) Descriptor() ([]byte, []int) {
	return file_trading_holding_proto_rawDescGZIP(), []int{4}
}

func (x *SellHoldingResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *SellHoldingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// SetHoldingPublic adjusts the public_amount counter on a stock holding. The
// schema CHECK pins public_amount to 0 for non-stock holdings — the server
// rejects any attempt to set it on a non-stock row with FailedPrecondition.
// 0 ≤ public_amount ≤ amount; out-of-range values come back as
// InvalidArgument so the portal can surface the problem inline.
type SetHoldingPublicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldingId     int64                  `protobuf:"varint,1,opt,name=holding_id,json=holdingId,proto3" json:"holding_id,omitempty"`
	PublicAmount  int64                  `protobuf:"varint,2,opt,name=public_amount,json=publicAmount,proto3" json:"public_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHoldingPublicRequest) Reset() {
	*x = SetHoldingPublicRequest{}
	mi := &file_trading_holding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHoldingPublicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHoldingPublicRequest) ProtoMessage() {}

func (x *SetHoldingPublicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_holding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHoldingPublicRequest.ProtoReflect.Descriptor instead.
func (*SetHoldingPublicRequest) Descriptor() ([]byte, []int) {
	return file_trading_holding_proto_rawDescGZIP(), []int{5}
}

func (x *SetHoldingPublicRequest) GetHoldingId() int64 {
	if x != nil {
		return x.HoldingId
	}
	return 0
}

func (x *SetHoldingPublicRequest) GetPublicAmount() int64 {
	if x != nil {
		return x.PublicAmount
	}
	return 0
}

type SetHoldingPublicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holding       *Holding               `protobuf:"bytes,1,opt,name=holding,proto3" json:"holding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHoldingPublicResponse) Reset() {
	*x = SetHoldingPublicResponse{}
	mi := &file_trading_holding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHoldingPublicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHoldingPublicResponse) ProtoMessage() {}

func (x *SetHoldingPublicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_holding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHoldingPublicResponse.ProtoReflect.Descriptor instead.
func (*SetHoldingPublicResponse) Descriptor() ([]byte, []int) {
	return file_trading_holding_proto_rawDescGZIP(), []int{6}
}

func (x *SetHoldingPublicResponse) GetHolding() *Holding {
	if x != nil {
		return x.Holding
	}
	return nil
}

var File_trading_holding_proto protoreflect.FileDescriptor

const file_trading_holding_proto_rawDesc = "" +
	"\n" +
	"\x15trading/holding.proto\x12\atrading\"\xef\x03\n" +
	"\aHolding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tplacer_id\x18\x02 \x01(\x03R\bplacerId\x12\x19\n" +
	"\bstock_id\x18\x03 \x01(\x03R\astockId\x12\x1b\n" +
	"\tfuture_id\x18\x04 \x01(\x03R\bfutureId\x12\"\n" +
	"\rforex_pair_id\x18\x05 \x01(\x03R\vforexPairId\x12\x1b\n" +
	"\toption_id\x18\x06 \x01(\x03R\boptionId\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12\x19\n" +
	"\bavg_cost\x18\b \x01(\x03R\aavgCost\x12\x1d\n" +
	"\n" +
	"account_id\x18\t \x01(\x03R\taccountId\x12%\n" +
	"\x0eaccount_number\x18\n" +
	" \x01(\tR\raccountNumber\x12#\n" +
	"\rpublic_amount\x18\v \x01(\x03R\fpublicAmount\x12\x16\n" +
	"\x06ticker\x18\f \x01(\tR\x06ticker\x12#\n" +
	"\rcurrent_price\x18\r \x01(\x03R\fcurrentPrice\x12\x16\n" +
	"\x06profit\x18\x0e \x01(\x03R\x06profit\x12,\n" +
	"\x12last_modified_unix\x18\x0f \x01(\x03R\x10lastModifiedUnix\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x10 \x01(\tR\tassetType\"8\n" +
	"\x13ListHoldingsRequest\x12!\n" +
	"\fcaller_email\x18\x01 \x01(\tR\vcallerEmail\"D\n" +
	"\x14ListHoldingsResponse\x12,\n" +
	"\bholdings\x18\x01 \x03(\v2\x10.trading.HoldingR\bholdings\"\xf5\x01\n" +
	"\x12SellHoldingRequest\x12\x1d\n" +
	"\n" +
	"holding_id\x18\x01 \x01(\x03R\tholdingId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12\x1d\n" +
	"\n" +
	"order_type\x18\x03 \x01(\tR\torderType\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x1f\n" +
	"\vlimit_price\x18\x05 \x01(\x03R\n" +
	"limitPrice\x12\x1d\n" +
	"\n" +
	"stop_price\x18\x06 \x01(\x03R\tstopPrice\x12\x1e\n" +
	"\vall_or_none\x18\a \x01(\bR\tallOrNone\"H\n" +
	"\x13SellHoldingResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"]\n" +
	"\x17SetHoldingPublicRequest\x12\x1d\n" +
	"\n" +
	"holding_id\x18\x01 \x01(\x03R\tholdingId\x12#\n" +
	"\rpublic_amount\x18\x02 \x01(\x03R\fpublicAmount\"F\n" +
	"\x18SetHoldingPublicResponse\x12*\n" +
	"\aholding\x18\x01 \x01(\v2\x10.trading.HoldingR\aholdingB:Z8github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/tradingb\x06proto3"

var (
	file_trading_holding_proto_rawDescOnce sync.Once
	file_trading_holding_proto_rawDescData []byte
)

func file_trading_holding_proto_rawDescGZIP() []byte {
	file_trading_holding_proto_rawDescOnce.Do(func() {
		file_trading_holding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_holding_proto_rawDesc), len(file_trading_holding_proto_rawDesc)))
	})
	return file_trading_holding_proto_rawDescData
}

var file_trading_holding_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_trading_holding_proto_goTypes = []any{
	(*Holding)(nil),                  // 0: trading.Holding
	(*ListHoldingsRequest)(nil),      // 1: trading.ListHoldingsRequest
	(*ListHoldingsResponse)(nil),     // 2: trading.ListHoldingsResponse
	(*SellHoldingRequest)(nil),       // 3: trading.SellHoldingRequest
	(*SellHoldingResponse)(nil),      // 4: trading.SellHoldingResponse
	(*SetHoldingPublicRequest)(nil),  // 5: trading.SetHoldingPublicRequest
	(*SetHoldingPublicResponse)(nil), // 6: trading.SetHoldingPublicResponse
}
var file_trading_holding_proto_depIdxs = []int32{
	0, // 0: trading.ListHoldingsResponse.holdings:type_name -> trading.Holding
	0, // 1: trading.SetHoldingPublicResponse.holding:type_name -> trading.Holding
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trading_holding_proto_init() }
func file_trading_holding_proto_init() {
	if File_trading_holding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_holding_proto_rawDesc), len(file_trading_holding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trading_holding_proto_goTypes,
		DependencyIndexes: file_trading_holding_proto_depIdxs,
		MessageInfos:      file_trading_holding_proto_msgTypes,
	}.Build()
	File_trading_holding_proto = out.File
	file_trading_holding_proto_goTypes = nil
	file_trading_holding_proto_depIdxs = nil
}
