// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: trading/option.proto

package trading

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Options attach to stocks directly (spec "Idea 1" — no options listings).
// Actuaries (employees) only; clients get PermissionDenied. Dates and grid
// are split into two calls so the stock detail page can render the expiry
// selector before fetching the grid (spec p.60).
type ListOptionDatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockId       int64                  `protobuf:"varint,1,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	CallerEmail   string                 `protobuf:"bytes,2,opt,name=caller_email,json=callerEmail,proto3" json:"caller_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOptionDatesRequest) Reset() {
	*x = ListOptionDatesRequest{}
	mi := &file_trading_option_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptionDatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptionDatesRequest) ProtoMessage() {}

func (x *ListOptionDatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_option_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptionDatesRequest.ProtoReflect.Descriptor instead.
func (*ListOptionDatesRequest) Descriptor() ([]byte, []int) {
	return file_trading_option_proto_rawDescGZIP(), []int{0}
}

func (x *ListOptionDatesRequest) GetStockId() int64 {
	if x != nil {
		return x.StockId
	}
	return 0
}

func (x *ListOptionDatesRequest) GetCallerEmail() string {
	if x != nil {
		return x.CallerEmail
	}
	return ""
}

type OptionDate struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SettlementDateUnix int64                  `protobuf:"varint,1,opt,name=settlement_date_unix,json=settlementDateUnix,proto3" json:"settlement_date_unix,omitempty"`
	DaysToExpiry       int32                  `protobuf:"varint,2,opt,name=days_to_expiry,json=daysToExpiry,proto3" json:"days_to_expiry,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OptionDate) Reset() {
	*x = OptionDate{}
	mi := &file_trading_option_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionDate) ProtoMessage() {}

func (x *OptionDate) ProtoReflect() protoreflect.Message {
	mi := &file_trading_option_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionDate.ProtoReflect.Descriptor instead.
func (*OptionDate) Descriptor() ([]byte, []int) {
	return file_trading_option_proto_rawDescGZIP(), []int{1}
}

func (x *OptionDate) GetSettlementDateUnix() int64 {
	if x != nil {
		return x.SettlementDateUnix
	}
	return 0
}

func (x *OptionDate) GetDaysToExpiry() int32 {
	if x != nil {
		return x.DaysToExpiry
	}
	return 0
}

type ListOptionDatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dates         []*OptionDate          `protobuf:"bytes,1,rep,name=dates,proto3" json:"dates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOptionDatesResponse) Reset() {
	*x = ListOptionDatesResponse{}
	mi := &file_trading_option_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptionDatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptionDatesResponse) ProtoMessage() {}

func (x *ListOptionDatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_option_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptionDatesResponse.ProtoReflect.Descriptor instead.
func (*ListOptionDatesResponse) Descriptor() ([]byte, []int) {
	return file_trading_option_proto_rawDescGZIP(), []int{2}
}

func (x *ListOptionDatesResponse) GetDates() []*OptionDate {
	if x != nil {
		return x.Dates
	}
	return nil
}

// strikes is the number of rows above AND below the current stock price; the
// response has at most 2*strikes+1 rows. settlement is the expiry to filter
// on, formatted YYYY-MM-DD.
type ListOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockId       int64                  `protobuf:"varint,1,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	Settlement    string                 `protobuf:"bytes,2,opt,name=settlement,proto3" json:"settlement,omitempty"`
	Strikes       int32                  `protobuf:"varint,3,opt,name=strikes,proto3" json:"strikes,omitempty"`
	CallerEmail   string                 `protobuf:"bytes,4,opt,name=caller_email,json=callerEmail,proto3" json:"caller_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOptionsRequest) Reset() {
	*x = ListOptionsRequest{}
	mi := &file_trading_option_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptionsRequest) ProtoMessage() {}

func (x *ListOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_option_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptionsRequest.ProtoReflect.Descriptor instead.
func (*ListOptionsRequest) Descriptor() ([]byte, []int) {
	return file_trading_option_proto_rawDescGZIP(), []int{3}
}

func (x *ListOptionsRequest) GetStockId() int64 {
	if x != nil {
		return x.StockId
	}
	return 0
}

func (x *ListOptionsRequest) GetSettlement() string {
	if x != nil {
		return x.Settlement
	}
	return ""
}

func (x *ListOptionsRequest) GetStrikes() int32 {
	if x != nil {
		return x.Strikes
	}
	return 0
}

func (x *ListOptionsRequest) GetCallerEmail() string {
	if x != nil {
		return x.CallerEmail
	}
	return ""
}

// OptionContract carries the fields rendered in the grid (spec p.60). theta,
// bid, ask and volume are stubbed to 0 until Black-Scholes + an options order
// book are wired (issue #197 explicitly allows stubs). last == premium.
type OptionContract struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ticker             string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Side               string                 `protobuf:"bytes,3,opt,name=side,proto3" json:"side,omitempty"`
	Strike             int64                  `protobuf:"varint,4,opt,name=strike,proto3" json:"strike,omitempty"`
	Last               int64                  `protobuf:"varint,5,opt,name=last,proto3" json:"last,omitempty"`
	Theta              int64                  `protobuf:"varint,6,opt,name=theta,proto3" json:"theta,omitempty"`
	Bid                int64                  `protobuf:"varint,7,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask                int64                  `protobuf:"varint,8,opt,name=ask,proto3" json:"ask,omitempty"`
	Volume             int64                  `protobuf:"varint,9,opt,name=volume,proto3" json:"volume,omitempty"`
	OpenInterest       int64                  `protobuf:"varint,10,opt,name=open_interest,json=openInterest,proto3" json:"open_interest,omitempty"`
	SettlementDateUnix int64                  `protobuf:"varint,11,opt,name=settlement_date_unix,json=settlementDateUnix,proto3" json:"settlement_date_unix,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OptionContract) Reset() {
	*x = OptionContract{}
	mi := &file_trading_option_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionContract) ProtoMessage() {}

func (x *OptionContract) ProtoReflect() protoreflect.Message {
	mi := &file_trading_option_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionContract.ProtoReflect.Descriptor instead.
func (*OptionContract) Descriptor() ([]byte, []int) {
	return file_trading_option_proto_rawDescGZIP(), []int{4}
}

func (x *OptionContract) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OptionContract) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *OptionContract) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *OptionContract) GetStrike() int64 {
	if x != nil {
		return x.Strike
	}
	return 0
}

func (x *OptionContract) GetLast() int64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *OptionContract) GetTheta() int64 {
	if x != nil {
		return x.Theta
	}
	return 0
}

func (x *OptionContract) GetBid() int64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *OptionContract) GetAsk() int64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *OptionContract) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *OptionContract) GetOpenInterest() int64 {
	if x != nil {
		return x.OpenInterest
	}
	return 0
}

func (x *OptionContract) GetSettlementDateUnix() int64 {
	if x != nil {
		return x.SettlementDateUnix
	}
	return 0
}

type OptionGridRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strike        int64                  `protobuf:"varint,1,opt,name=strike,proto3" json:"strike,omitempty"`
	Call          *OptionContract        `protobuf:"bytes,2,opt,name=call,proto3" json:"call,omitempty"`
	Put           *OptionContract        `protobuf:"bytes,3,opt,name=put,proto3" json:"put,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionGridRow) Reset() {
	*x = OptionGridRow{}
	mi := &file_trading_option_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionGridRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionGridRow) ProtoMessage() {}

func (x *OptionGridRow) ProtoReflect() protoreflect.Message {
	mi := &file_trading_option_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionGridRow.ProtoReflect.Descriptor instead.
func (*OptionGridRow) Descriptor() ([]byte, []int) {
	return file_trading_option_proto_rawDescGZIP(), []int{5}
}

func (x *OptionGridRow) GetStrike() int64 {
	if x != nil {
		return x.Strike
	}
	return 0
}

func (x *OptionGridRow) GetCall() *OptionContract {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *OptionGridRow) GetPut() *OptionContract {
	if x != nil {
		return x.Put
	}
	return nil
}

type ListOptionsResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StockId    int64                  `protobuf:"varint,1,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	Settlement string                 `protobuf:"bytes,2,opt,name=settlement,proto3" json:"settlement,omitempty"`
	// shared_price is the current stock listing price, rendered once above the
	// grid (spec p.60 "cena akcije iznad tabele").
	SharedPrice   int64            `protobuf:"varint,3,opt,name=shared_price,json=sharedPrice,proto3" json:"shared_price,omitempty"`
	Rows          []*OptionGridRow `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOptionsResponse) Reset() {
	*x = ListOptionsResponse{}
	mi := &file_trading_option_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptionsResponse) ProtoMessage() {}

func (x *ListOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_option_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptionsResponse.ProtoReflect.Descriptor instead.
func (*ListOptionsResponse) Descriptor() ([]byte, []int) {
	return file_trading_option_proto_rawDescGZIP(), []int{6}
}

func (x *ListOptionsResponse) GetStockId() int64 {
	if x != nil {
		return x.StockId
	}
	return 0
}

func (x *ListOptionsResponse) GetSettlement() string {
	if x != nil {
		return x.Settlement
	}
	return ""
}

func (x *ListOptionsResponse) GetSharedPrice() int64 {
	if x != nil {
		return x.SharedPrice
	}
	return 0
}

func (x *ListOptionsResponse) GetRows() []*OptionGridRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

// ExerciseOption settles an option held by the caller. Actuary-only, the
// option must not be past settlement, and it has to be in-the-money — calls
// fire when spot > strike, puts when strike > spot. Payout per spec p.62:
//   call: (spot - strike) * contract_size * quantity − premium * quantity
//   put : (strike - spot) * contract_size * quantity − premium * quantity
// The premium is paid back per contract held (not just once) — the user
// effectively recoups what they paid to acquire the position. Settlement is
// against the account_number passed in, which must belong to the caller.
type ExerciseOptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionId      int64                  `protobuf:"varint,1,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseOptionRequest) Reset() {
	*x = ExerciseOptionRequest{}
	mi := &file_trading_option_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseOptionRequest) ProtoMessage() {}

func (x *ExerciseOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_option_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseOptionRequest.ProtoReflect.Descriptor instead.
func (*ExerciseOptionRequest) Descriptor() ([]byte, []int) {
	return file_trading_option_proto_rawDescGZIP(), []int{7}
}

func (x *ExerciseOptionRequest) GetOptionId() int64 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

func (x *ExerciseOptionRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type ExerciseOptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payout        int64                  `protobuf:"varint,1,opt,name=payout,proto3" json:"payout,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseOptionResponse) Reset() {
	*x = ExerciseOptionResponse{}
	mi := &file_trading_option_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseOptionResponse) ProtoMessage() {}

func (x *ExerciseOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_option_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseOptionResponse.ProtoReflect.Descriptor instead.
func (*ExerciseOptionResponse) Descriptor() ([]byte, []int) {
	return file_trading_option_proto_rawDescGZIP(), []int{8}
}

func (x *ExerciseOptionResponse) GetPayout() int64 {
	if x != nil {
		return x.Payout
	}
	return 0
}

func (x *ExerciseOptionResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_trading_option_proto protoreflect.FileDescriptor

const file_trading_option_proto_rawDesc = "" +
	"\n" +
	"\x14trading/option.proto\x12\atrading\"V\n" +
	"\x16ListOptionDatesRequest\x12\x19\n" +
	"\bstock_id\x18\x01 \x01(\x03R\astockId\x12!\n" +
	"\fcaller_email\x18\x02 \x01(\tR\vcallerEmail\"d\n" +
	"\n" +
	"OptionDate\x120\n" +
	"\x14settlement_date_unix\x18\x01 \x01(\x03R\x12settlementDateUnix\x12$\n" +
	"\x0edays_to_expiry\x18\x02 \x01(\x05R\fdaysToExpiry\"D\n" +
	"\x17ListOptionDatesResponse\x12)\n" +
	"\x05dates\x18\x01 \x03(\v2\x13.trading.OptionDateR\x05dates\"\x8c\x01\n" +
	"\x12ListOptionsRequest\x12\x19\n" +
	"\bstock_id\x18\x01 \x01(\x03R\astockId\x12\x1e\n" +
	"\n" +
	"settlement\x18\x02 \x01(\tR\n" +
	"settlement\x12\x18\n" +
	"\astrikes\x18\x03 \x01(\x05R\astrikes\x12!\n" +
	"\fcaller_email\x18\x04 \x01(\tR\vcallerEmail\"\xa1\x02\n" +
	"\x0eOptionContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12\x12\n" +
	"\x04side\x18\x03 \x01(\tR\x04side\x12\x16\n" +
	"\x06strike\x18\x04 \x01(\x03R\x06strike\x12\x12\n" +
	"\x04last\x18\x05 \x01(\x03R\x04last\x12\x14\n" +
	"\x05theta\x18\x06 \x01(\x03R\x05theta\x12\x10\n" +
	"\x03bid\x18\a \x01(\x03R\x03bid\x12\x10\n" +
	"\x03ask\x18\b \x01(\x03R\x03ask\x12\x16\n" +
	"\x06volume\x18\t \x01(\x03R\x06volume\x12#\n" +
	"\ropen_interest\x18\n" +
	" \x01(\x03R\fopenInterest\x120\n" +
	"\x14settlement_date_unix\x18\v \x01(\x03R\x12settlementDateUnix\"\x7f\n" +
	"\rOptionGridRow\x12\x16\n" +
	"\x06strike\x18\x01 \x01(\x03R\x06strike\x12+\n" +
	"\x04call\x18\x02 \x01(\v2\x17.trading.OptionContractR\x04call\x12)\n" +
	"\x03put\x18\x03 \x01(\v2\x17.trading.OptionContractR\x03put\"\x9f\x01\n" +
	"\x13ListOptionsResponse\x12\x19\n" +
	"\bstock_id\x18\x01 \x01(\x03R\astockId\x12\x1e\n" +
	"\n" +
	"settlement\x18\x02 \x01(\tR\n" +
	"settlement\x12!\n" +
	"\fshared_price\x18\x03 \x01(\x03R\vsharedPrice\x12*\n" +
	"\x04rows\x18\x04 \x03(\v2\x16.trading.OptionGridRowR\x04rows\"[\n" +
	"\x15ExerciseOptionRequest\x12\x1b\n" +
	"\toption_id\x18\x01 \x01(\x03R\boptionId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\"L\n" +
	"\x16ExerciseOptionResponse\x12\x16\n" +
	"\x06payout\x18\x01 \x01(\x03R\x06payout\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantityB:Z8github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/tradingb\x06proto3"

var (
	file_trading_option_proto_rawDescOnce sync.Once
	file_trading_option_proto_rawDescData []byte
)

func file_trading_option_proto_rawDescGZIP() []byte {
	file_trading_option_proto_rawDescOnce.Do(func() {
		file_trading_option_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_option_proto_rawDesc), len(file_trading_option_proto_rawDesc)))
	})
	return file_trading_option_proto_rawDescData
}

var file_trading_option_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_trading_option_proto_goTypes = []any{
	(*ListOptionDatesRequest)(nil),  // 0: trading.ListOptionDatesRequest
	(*OptionDate)(nil),              // 1: trading.OptionDate
	(*ListOptionDatesResponse)(nil), // 2: trading.ListOptionDatesResponse
	(*ListOptionsRequest)(nil),      // 3: trading.ListOptionsRequest
	(*OptionContract)(nil),          // 4: trading.OptionContract
	(*OptionGridRow)(nil),           // 5: trading.OptionGridRow
	(*ListOptionsResponse)(nil),     // 6: trading.ListOptionsResponse
	(*ExerciseOptionRequest)(nil),   // 7: trading.ExerciseOptionRequest
	(*ExerciseOptionResponse)(nil),  // 8: trading.ExerciseOptionResponse
}
var file_trading_option_proto_depIdxs = []int32{
	1, // 0: trading.ListOptionDatesResponse.dates:type_name -> trading.OptionDate
	4, // 1: trading.OptionGridRow.call:type_name -> trading.OptionContract
	4, // 2: trading.OptionGridRow.put:type_name -> trading.OptionContract
	5, // 3: trading.ListOptionsResponse.rows:type_name -> trading.OptionGridRow
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_trading_option_proto_init() }
func file_trading_option_proto_init() {
	if File_trading_option_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_option_proto_rawDesc), len(file_trading_option_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trading_option_proto_goTypes,
		DependencyIndexes: file_trading_option_proto_depIdxs,
		MessageInfos:      file_trading_option_proto_msgTypes,
	}.Build()
	File_trading_option_proto = out.File
	file_trading_option_proto_goTypes = nil
	file_trading_option_proto_depIdxs = nil
}
