// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: trading/order.proto

package trading

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Exactly one of listing_id / option_id / forex_pair_id must be set — that's
// the instrument being traded. limit_price / stop_price are required only
// for LIMIT / STOP / STOP_LIMIT; senders must leave them 0 otherwise.
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     int64                  `protobuf:"varint,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	OptionId      int64                  `protobuf:"varint,2,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	ForexPairId   int64                  `protobuf:"varint,3,opt,name=forex_pair_id,json=forexPairId,proto3" json:"forex_pair_id,omitempty"`
	AccountNumber string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	OrderType     string                 `protobuf:"bytes,5,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Direction     string                 `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	Quantity      int64                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LimitPrice    int64                  `protobuf:"varint,8,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	StopPrice     int64                  `protobuf:"varint,9,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	AllOrNone     bool                   `protobuf:"varint,10,opt,name=all_or_none,json=allOrNone,proto3" json:"all_or_none,omitempty"`
	Margin        bool                   `protobuf:"varint,11,opt,name=margin,proto3" json:"margin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_trading_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

func (x *CreateOrderRequest) GetOptionId() int64 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

func (x *CreateOrderRequest) GetForexPairId() int64 {
	if x != nil {
		return x.ForexPairId
	}
	return 0
}

func (x *CreateOrderRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *CreateOrderRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *CreateOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderRequest) GetLimitPrice() int64 {
	if x != nil {
		return x.LimitPrice
	}
	return 0
}

func (x *CreateOrderRequest) GetStopPrice() int64 {
	if x != nil {
		return x.StopPrice
	}
	return 0
}

func (x *CreateOrderRequest) GetAllOrNone() bool {
	if x != nil {
		return x.AllOrNone
	}
	return false
}

func (x *CreateOrderRequest) GetMargin() bool {
	if x != nil {
		return x.Margin
	}
	return false
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_trading_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_trading_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// OrderDetail is the row shape used by the supervisor orders portal (spec
// pp.57–58). asset_label is a human-readable instrument identifier: the
// listing's ticker for stocks/futures, the option or forex-pair ticker
// otherwise. placer_name is derived from the placer row (employee or client).
// past_settlement signals "approve blocked, decline only" at the UI layer —
// the RPC re-checks server-side.
type OrderDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OrderType         string                 `protobuf:"bytes,3,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Direction         string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Quantity          int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ContractSize      int64                  `protobuf:"varint,6,opt,name=contract_size,json=contractSize,proto3" json:"contract_size,omitempty"`
	PricePerUnit      int64                  `protobuf:"varint,7,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	RemainingPortions int64                  `protobuf:"varint,8,opt,name=remaining_portions,json=remainingPortions,proto3" json:"remaining_portions,omitempty"`
	AssetLabel        string                 `protobuf:"bytes,9,opt,name=asset_label,json=assetLabel,proto3" json:"asset_label,omitempty"`
	PlacerName        string                 `protobuf:"bytes,10,opt,name=placer_name,json=placerName,proto3" json:"placer_name,omitempty"`
	PlacerEmployeeId  int64                  `protobuf:"varint,11,opt,name=placer_employee_id,json=placerEmployeeId,proto3" json:"placer_employee_id,omitempty"`
	PlacerClientId    int64                  `protobuf:"varint,12,opt,name=placer_client_id,json=placerClientId,proto3" json:"placer_client_id,omitempty"`
	PastSettlement    bool                   `protobuf:"varint,13,opt,name=past_settlement,json=pastSettlement,proto3" json:"past_settlement,omitempty"`
	ApprovedBy        int64                  `protobuf:"varint,14,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	CreatedAtUnix     int64                  `protobuf:"varint,15,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Margin            bool                   `protobuf:"varint,16,opt,name=margin,proto3" json:"margin,omitempty"`
	AllOrNone         bool                   `protobuf:"varint,17,opt,name=all_or_none,json=allOrNone,proto3" json:"all_or_none,omitempty"`
	Commission        int64                  `protobuf:"varint,18,opt,name=commission,proto3" json:"commission,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderDetail) Reset() {
	*x = OrderDetail{}
	mi := &file_trading_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail) ProtoMessage() {}

func (x *OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail.ProtoReflect.Descriptor instead.
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return file_trading_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderDetail) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *OrderDetail) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *OrderDetail) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderDetail) GetContractSize() int64 {
	if x != nil {
		return x.ContractSize
	}
	return 0
}

func (x *OrderDetail) GetPricePerUnit() int64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *OrderDetail) GetRemainingPortions() int64 {
	if x != nil {
		return x.RemainingPortions
	}
	return 0
}

func (x *OrderDetail) GetAssetLabel() string {
	if x != nil {
		return x.AssetLabel
	}
	return ""
}

func (x *OrderDetail) GetPlacerName() string {
	if x != nil {
		return x.PlacerName
	}
	return ""
}

func (x *OrderDetail) GetPlacerEmployeeId() int64 {
	if x != nil {
		return x.PlacerEmployeeId
	}
	return 0
}

func (x *OrderDetail) GetPlacerClientId() int64 {
	if x != nil {
		return x.PlacerClientId
	}
	return 0
}

func (x *OrderDetail) GetPastSettlement() bool {
	if x != nil {
		return x.PastSettlement
	}
	return false
}

func (x *OrderDetail) GetApprovedBy() int64 {
	if x != nil {
		return x.ApprovedBy
	}
	return 0
}

func (x *OrderDetail) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *OrderDetail) GetMargin() bool {
	if x != nil {
		return x.Margin
	}
	return false
}

func (x *OrderDetail) GetAllOrNone() bool {
	if x != nil {
		return x.AllOrNone
	}
	return false
}

func (x *OrderDetail) GetCommission() int64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

// Supervisor-only. status: "" or "all" returns every order, otherwise one of
// "pending|approved|declined|done|cancelled". agent_id filters by the placer's
// employee_id (0 = no filter); client-placed orders are excluded when a
// positive agent_id is passed.
type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerEmail   string                 `protobuf:"bytes,1,opt,name=caller_email,json=callerEmail,proto3" json:"caller_email,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AgentId       int64                  `protobuf:"varint,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_trading_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_trading_order_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrdersRequest) GetCallerEmail() string {
	if x != nil {
		return x.CallerEmail
	}
	return ""
}

func (x *ListOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListOrdersRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderDetail         `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_trading_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_trading_order_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrdersResponse) GetOrders() []*OrderDetail {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ApproveOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CallerEmail   string                 `protobuf:"bytes,2,opt,name=caller_email,json=callerEmail,proto3" json:"caller_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveOrderRequest) Reset() {
	*x = ApproveOrderRequest{}
	mi := &file_trading_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveOrderRequest) ProtoMessage() {}

func (x *ApproveOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveOrderRequest.ProtoReflect.Descriptor instead.
func (*ApproveOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_order_proto_rawDescGZIP(), []int{5}
}

func (x *ApproveOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ApproveOrderRequest) GetCallerEmail() string {
	if x != nil {
		return x.CallerEmail
	}
	return ""
}

type ApproveOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderDetail           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveOrderResponse) Reset() {
	*x = ApproveOrderResponse{}
	mi := &file_trading_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveOrderResponse) ProtoMessage() {}

func (x *ApproveOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveOrderResponse.ProtoReflect.Descriptor instead.
func (*ApproveOrderResponse) Descriptor() ([]byte, []int) {
	return file_trading_order_proto_rawDescGZIP(), []int{6}
}

func (x *ApproveOrderResponse) GetOrder() *OrderDetail {
	if x != nil {
		return x.Order
	}
	return nil
}

type DeclineOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CallerEmail   string                 `protobuf:"bytes,2,opt,name=caller_email,json=callerEmail,proto3" json:"caller_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineOrderRequest) Reset() {
	*x = DeclineOrderRequest{}
	mi := &file_trading_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineOrderRequest) ProtoMessage() {}

func (x *DeclineOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineOrderRequest.ProtoReflect.Descriptor instead.
func (*DeclineOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_order_proto_rawDescGZIP(), []int{7}
}

func (x *DeclineOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *DeclineOrderRequest) GetCallerEmail() string {
	if x != nil {
		return x.CallerEmail
	}
	return ""
}

type DeclineOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderDetail           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineOrderResponse) Reset() {
	*x = DeclineOrderResponse{}
	mi := &file_trading_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineOrderResponse) ProtoMessage() {}

func (x *DeclineOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineOrderResponse.ProtoReflect.Descriptor instead.
func (*DeclineOrderResponse) Descriptor() ([]byte, []int) {
	return file_trading_order_proto_rawDescGZIP(), []int{8}
}

func (x *DeclineOrderResponse) GetOrder() *OrderDetail {
	if x != nil {
		return x.Order
	}
	return nil
}

// CancelOrder accepts either the order's owner or a supervisor. The caller
// identity comes from the `user-email` gRPC metadata header (same as
// CreateOrder) so the server can distinguish client owner vs. employee owner
// vs. supervisor without an extra DB round trip on the gateway.
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_trading_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_order_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderDetail           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_trading_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_trading_order_proto_rawDescGZIP(), []int{10}
}

func (x *CancelOrderResponse) GetOrder() *OrderDetail {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_trading_order_proto protoreflect.FileDescriptor

const file_trading_order_proto_rawDesc = "" +
	"\n" +
	"\x13trading/order.proto\x12\atrading\"\xec\x02\n" +
	"\x12CreateOrderRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\x03R\tlistingId\x12\x1b\n" +
	"\toption_id\x18\x02 \x01(\x03R\boptionId\x12\"\n" +
	"\rforex_pair_id\x18\x03 \x01(\x03R\vforexPairId\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\x12\x1d\n" +
	"\n" +
	"order_type\x18\x05 \x01(\tR\torderType\x12\x1c\n" +
	"\tdirection\x18\x06 \x01(\tR\tdirection\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x03R\bquantity\x12\x1f\n" +
	"\vlimit_price\x18\b \x01(\x03R\n" +
	"limitPrice\x12\x1d\n" +
	"\n" +
	"stop_price\x18\t \x01(\x03R\tstopPrice\x12\x1e\n" +
	"\vall_or_none\x18\n" +
	" \x01(\bR\tallOrNone\x12\x16\n" +
	"\x06margin\x18\v \x01(\bR\x06margin\"H\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xec\x04\n" +
	"\vOrderDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"order_type\x18\x03 \x01(\tR\torderType\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12#\n" +
	"\rcontract_size\x18\x06 \x01(\x03R\fcontractSize\x12$\n" +
	"\x0eprice_per_unit\x18\a \x01(\x03R\fpricePerUnit\x12-\n" +
	"\x12remaining_portions\x18\b \x01(\x03R\x11remainingPortions\x12\x1f\n" +
	"\vasset_label\x18\t \x01(\tR\n" +
	"assetLabel\x12\x1f\n" +
	"\vplacer_name\x18\n" +
	" \x01(\tR\n" +
	"placerName\x12,\n" +
	"\x12placer_employee_id\x18\v \x01(\x03R\x10placerEmployeeId\x12(\n" +
	"\x10placer_client_id\x18\f \x01(\x03R\x0eplacerClientId\x12'\n" +
	"\x0fpast_settlement\x18\r \x01(\bR\x0epastSettlement\x12\x1f\n" +
	"\vapproved_by\x18\x0e \x01(\x03R\n" +
	"approvedBy\x12&\n" +
	"\x0fcreated_at_unix\x18\x0f \x01(\x03R\rcreatedAtUnix\x12\x16\n" +
	"\x06margin\x18\x10 \x01(\bR\x06margin\x12\x1e\n" +
	"\vall_or_none\x18\x11 \x01(\bR\tallOrNone\x12\x1e\n" +
	"\n" +
	"commission\x18\x12 \x01(\x03R\n" +
	"commission\"i\n" +
	"\x11ListOrdersRequest\x12!\n" +
	"\fcaller_email\x18\x01 \x01(\tR\vcallerEmail\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\x03R\aagentId\"B\n" +
	"\x12ListOrdersResponse\x12,\n" +
	"\x06orders\x18\x01 \x03(\v2\x14.trading.OrderDetailR\x06orders\"S\n" +
	"\x13ApproveOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12!\n" +
	"\fcaller_email\x18\x02 \x01(\tR\vcallerEmail\"B\n" +
	"\x14ApproveOrderResponse\x12*\n" +
	"\x05order\x18\x01 \x01(\v2\x14.trading.OrderDetailR\x05order\"S\n" +
	"\x13DeclineOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12!\n" +
	"\fcaller_email\x18\x02 \x01(\tR\vcallerEmail\"B\n" +
	"\x14DeclineOrderResponse\x12*\n" +
	"\x05order\x18\x01 \x01(\v2\x14.trading.OrderDetailR\x05order\"/\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"A\n" +
	"\x13CancelOrderResponse\x12*\n" +
	"\x05order\x18\x01 \x01(\v2\x14.trading.OrderDetailR\x05orderB:Z8github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/tradingb\x06proto3"

var (
	file_trading_order_proto_rawDescOnce sync.Once
	file_trading_order_proto_rawDescData []byte
)

func file_trading_order_proto_rawDescGZIP() []byte {
	file_trading_order_proto_rawDescOnce.Do(func() {
		file_trading_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_order_proto_rawDesc), len(file_trading_order_proto_rawDesc)))
	})
	return file_trading_order_proto_rawDescData
}

var file_trading_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_trading_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),   // 0: trading.CreateOrderRequest
	(*CreateOrderResponse)(nil),  // 1: trading.CreateOrderResponse
	(*OrderDetail)(nil),          // 2: trading.OrderDetail
	(*ListOrdersRequest)(nil),    // 3: trading.ListOrdersRequest
	(*ListOrdersResponse)(nil),   // 4: trading.ListOrdersResponse
	(*ApproveOrderRequest)(nil),  // 5: trading.ApproveOrderRequest
	(*ApproveOrderResponse)(nil), // 6: trading.ApproveOrderResponse
	(*DeclineOrderRequest)(nil),  // 7: trading.DeclineOrderRequest
	(*DeclineOrderResponse)(nil), // 8: trading.DeclineOrderResponse
	(*CancelOrderRequest)(nil),   // 9: trading.CancelOrderRequest
	(*CancelOrderResponse)(nil),  // 10: trading.CancelOrderResponse
}
var file_trading_order_proto_depIdxs = []int32{
	2, // 0: trading.ListOrdersResponse.orders:type_name -> trading.OrderDetail
	2, // 1: trading.ApproveOrderResponse.order:type_name -> trading.OrderDetail
	2, // 2: trading.DeclineOrderResponse.order:type_name -> trading.OrderDetail
	2, // 3: trading.CancelOrderResponse.order:type_name -> trading.OrderDetail
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_trading_order_proto_init() }
func file_trading_order_proto_init() {
	if File_trading_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_order_proto_rawDesc), len(file_trading_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trading_order_proto_goTypes,
		DependencyIndexes: file_trading_order_proto_depIdxs,
		MessageInfos:      file_trading_order_proto_msgTypes,
	}.Build()
	File_trading_order_proto = out.File
	file_trading_order_proto_goTypes = nil
	file_trading_order_proto_depIdxs = nil
}
