// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: trading/tax.proto

package trading

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supervisor-only manual trigger for the monthly capital-gains tax sweep
// (spec p.63 "Supervizori mogu ručno pokrenuti ovu operaciju putem portala").
// month is YYYY-MM; passing an empty string sweeps every still-unpaid row
// regardless of period — useful for back-fills.
type RunCapitalGainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerEmail   string                 `protobuf:"bytes,1,opt,name=caller_email,json=callerEmail,proto3" json:"caller_email,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCapitalGainsRequest) Reset() {
	*x = RunCapitalGainsRequest{}
	mi := &file_trading_tax_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCapitalGainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCapitalGainsRequest) ProtoMessage() {}

func (x *RunCapitalGainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_tax_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCapitalGainsRequest.ProtoReflect.Descriptor instead.
func (*RunCapitalGainsRequest) Descriptor() ([]byte, []int) {
	return file_trading_tax_proto_rawDescGZIP(), []int{0}
}

func (x *RunCapitalGainsRequest) GetCallerEmail() string {
	if x != nil {
		return x.CallerEmail
	}
	return ""
}

func (x *RunCapitalGainsRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

type RunCapitalGainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	AccountsPaid  int32                  `protobuf:"varint,2,opt,name=accounts_paid,json=accountsPaid,proto3" json:"accounts_paid,omitempty"`
	RowsPaid      int32                  `protobuf:"varint,3,opt,name=rows_paid,json=rowsPaid,proto3" json:"rows_paid,omitempty"`
	Insufficient  int32                  `protobuf:"varint,4,opt,name=insufficient,proto3" json:"insufficient,omitempty"`
	TotalDebtRsd  int64                  `protobuf:"varint,5,opt,name=total_debt_rsd,json=totalDebtRsd,proto3" json:"total_debt_rsd,omitempty"`
	CollectedRsd  int64                  `protobuf:"varint,6,opt,name=collected_rsd,json=collectedRsd,proto3" json:"collected_rsd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCapitalGainsResponse) Reset() {
	*x = RunCapitalGainsResponse{}
	mi := &file_trading_tax_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCapitalGainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCapitalGainsResponse) ProtoMessage() {}

func (x *RunCapitalGainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_tax_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCapitalGainsResponse.ProtoReflect.Descriptor instead.
func (*RunCapitalGainsResponse) Descriptor() ([]byte, []int) {
	return file_trading_tax_proto_rawDescGZIP(), []int{1}
}

func (x *RunCapitalGainsResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *RunCapitalGainsResponse) GetAccountsPaid() int32 {
	if x != nil {
		return x.AccountsPaid
	}
	return 0
}

func (x *RunCapitalGainsResponse) GetRowsPaid() int32 {
	if x != nil {
		return x.RowsPaid
	}
	return 0
}

func (x *RunCapitalGainsResponse) GetInsufficient() int32 {
	if x != nil {
		return x.Insufficient
	}
	return 0
}

func (x *RunCapitalGainsResponse) GetTotalDebtRsd() int64 {
	if x != nil {
		return x.TotalDebtRsd
	}
	return 0
}

func (x *RunCapitalGainsResponse) GetCollectedRsd() int64 {
	if x != nil {
		return x.CollectedRsd
	}
	return 0
}

// TaxDebtor is one user's current unpaid RSD tax debt summed across all of
// their accounts (spec p.63: "Dugovanja korisnika prikazana su u RSD"). team
// is "client" or "actuary". Users without any capital-gains rows are not
// listed — the portal scopes itself to participants in the trading flow.
type TaxDebtor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Team          string                 `protobuf:"bytes,4,opt,name=team,proto3" json:"team,omitempty"`
	UnpaidRsd     int64                  `protobuf:"varint,5,opt,name=unpaid_rsd,json=unpaidRsd,proto3" json:"unpaid_rsd,omitempty"`
	PaidRsd       int64                  `protobuf:"varint,6,opt,name=paid_rsd,json=paidRsd,proto3" json:"paid_rsd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaxDebtor) Reset() {
	*x = TaxDebtor{}
	mi := &file_trading_tax_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaxDebtor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaxDebtor) ProtoMessage() {}

func (x *TaxDebtor) ProtoReflect() protoreflect.Message {
	mi := &file_trading_tax_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaxDebtor.ProtoReflect.Descriptor instead.
func (*TaxDebtor) Descriptor() ([]byte, []int) {
	return file_trading_tax_proto_rawDescGZIP(), []int{2}
}

func (x *TaxDebtor) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TaxDebtor) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *TaxDebtor) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *TaxDebtor) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *TaxDebtor) GetUnpaidRsd() int64 {
	if x != nil {
		return x.UnpaidRsd
	}
	return 0
}

func (x *TaxDebtor) GetPaidRsd() int64 {
	if x != nil {
		return x.PaidRsd
	}
	return 0
}

// Filters mirror the spec's two portal filters: team (klijent/aktuar) and
// name (case-insensitive substring on first or last name). Empty values
// disable the corresponding filter.
type ListTaxDebtsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerEmail   string                 `protobuf:"bytes,1,opt,name=caller_email,json=callerEmail,proto3" json:"caller_email,omitempty"`
	Team          string                 `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaxDebtsRequest) Reset() {
	*x = ListTaxDebtsRequest{}
	mi := &file_trading_tax_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaxDebtsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaxDebtsRequest) ProtoMessage() {}

func (x *ListTaxDebtsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_tax_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaxDebtsRequest.ProtoReflect.Descriptor instead.
func (*ListTaxDebtsRequest) Descriptor() ([]byte, []int) {
	return file_trading_tax_proto_rawDescGZIP(), []int{3}
}

func (x *ListTaxDebtsRequest) GetCallerEmail() string {
	if x != nil {
		return x.CallerEmail
	}
	return ""
}

func (x *ListTaxDebtsRequest) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *ListTaxDebtsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListTaxDebtsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Debtors       []*TaxDebtor           `protobuf:"bytes,1,rep,name=debtors,proto3" json:"debtors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaxDebtsResponse) Reset() {
	*x = ListTaxDebtsResponse{}
	mi := &file_trading_tax_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaxDebtsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaxDebtsResponse) ProtoMessage() {}

func (x *ListTaxDebtsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_tax_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaxDebtsResponse.ProtoReflect.Descriptor instead.
func (*ListTaxDebtsResponse) Descriptor() ([]byte, []int) {
	return file_trading_tax_proto_rawDescGZIP(), []int{4}
}

func (x *ListTaxDebtsResponse) GetDebtors() []*TaxDebtor {
	if x != nil {
		return x.Debtors
	}
	return nil
}

// GetMyTaxInfo backs the Moj Portfolio tax widget (spec p.61). Caller identity
// is read from the `user-email` gRPC metadata via bank.ResolveCaller; any
// authenticated client or actuary may call it. paid_this_year_rsd sums tax
// rows whose paid_at falls in the current calendar year; unpaid_this_month_rsd
// sums every still-unpaid row (the cron sweeps monthly, so "tekući mesec" and
// "all unpaid" coincide in practice).
type GetMyTaxInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerEmail   string                 `protobuf:"bytes,1,opt,name=caller_email,json=callerEmail,proto3" json:"caller_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyTaxInfoRequest) Reset() {
	*x = GetMyTaxInfoRequest{}
	mi := &file_trading_tax_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyTaxInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyTaxInfoRequest) ProtoMessage() {}

func (x *GetMyTaxInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_tax_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyTaxInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMyTaxInfoRequest) Descriptor() ([]byte, []int) {
	return file_trading_tax_proto_rawDescGZIP(), []int{5}
}

func (x *GetMyTaxInfoRequest) GetCallerEmail() string {
	if x != nil {
		return x.CallerEmail
	}
	return ""
}

type GetMyTaxInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PaidThisYearRsd    int64                  `protobuf:"varint,1,opt,name=paid_this_year_rsd,json=paidThisYearRsd,proto3" json:"paid_this_year_rsd,omitempty"`
	UnpaidThisMonthRsd int64                  `protobuf:"varint,2,opt,name=unpaid_this_month_rsd,json=unpaidThisMonthRsd,proto3" json:"unpaid_this_month_rsd,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetMyTaxInfoResponse) Reset() {
	*x = GetMyTaxInfoResponse{}
	mi := &file_trading_tax_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyTaxInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyTaxInfoResponse) ProtoMessage() {}

func (x *GetMyTaxInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_tax_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyTaxInfoResponse.ProtoReflect.Descriptor instead.
func (*GetMyTaxInfoResponse) Descriptor() ([]byte, []int) {
	return file_trading_tax_proto_rawDescGZIP(), []int{6}
}

func (x *GetMyTaxInfoResponse) GetPaidThisYearRsd() int64 {
	if x != nil {
		return x.PaidThisYearRsd
	}
	return 0
}

func (x *GetMyTaxInfoResponse) GetUnpaidThisMonthRsd() int64 {
	if x != nil {
		return x.UnpaidThisMonthRsd
	}
	return 0
}

var File_trading_tax_proto protoreflect.FileDescriptor

const file_trading_tax_proto_rawDesc = "" +
	"\n" +
	"\x11trading/tax.proto\x12\atrading\"Q\n" +
	"\x16RunCapitalGainsRequest\x12!\n" +
	"\fcaller_email\x18\x01 \x01(\tR\vcallerEmail\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\"\xe2\x01\n" +
	"\x17RunCapitalGainsResponse\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12#\n" +
	"\raccounts_paid\x18\x02 \x01(\x05R\faccountsPaid\x12\x1b\n" +
	"\trows_paid\x18\x03 \x01(\x05R\browsPaid\x12\"\n" +
	"\finsufficient\x18\x04 \x01(\x05R\finsufficient\x12$\n" +
	"\x0etotal_debt_rsd\x18\x05 \x01(\x03R\ftotalDebtRsd\x12#\n" +
	"\rcollected_rsd\x18\x06 \x01(\x03R\fcollectedRsd\"\xae\x01\n" +
	"\tTaxDebtor\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x12\n" +
	"\x04team\x18\x04 \x01(\tR\x04team\x12\x1d\n" +
	"\n" +
	"unpaid_rsd\x18\x05 \x01(\x03R\tunpaidRsd\x12\x19\n" +
	"\bpaid_rsd\x18\x06 \x01(\x03R\apaidRsd\"`\n" +
	"\x13ListTaxDebtsRequest\x12!\n" +
	"\fcaller_email\x18\x01 \x01(\tR\vcallerEmail\x12\x12\n" +
	"\x04team\x18\x02 \x01(\tR\x04team\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"D\n" +
	"\x14ListTaxDebtsResponse\x12,\n" +
	"\adebtors\x18\x01 \x03(\v2\x12.trading.TaxDebtorR\adebtors\"8\n" +
	"\x13GetMyTaxInfoRequest\x12!\n" +
	"\fcaller_email\x18\x01 \x01(\tR\vcallerEmail\"v\n" +
	"\x14GetMyTaxInfoResponse\x12+\n" +
	"\x12paid_this_year_rsd\x18\x01 \x01(\x03R\x0fpaidThisYearRsd\x121\n" +
	"\x15unpaid_this_month_rsd\x18\x02 \x01(\x03R\x12unpaidThisMonthRsdB:Z8github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/tradingb\x06proto3"

var (
	file_trading_tax_proto_rawDescOnce sync.Once
	file_trading_tax_proto_rawDescData []byte
)

func file_trading_tax_proto_rawDescGZIP() []byte {
	file_trading_tax_proto_rawDescOnce.Do(func() {
		file_trading_tax_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_tax_proto_rawDesc), len(file_trading_tax_proto_rawDesc)))
	})
	return file_trading_tax_proto_rawDescData
}

var file_trading_tax_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_trading_tax_proto_goTypes = []any{
	(*RunCapitalGainsRequest)(nil),  // 0: trading.RunCapitalGainsRequest
	(*RunCapitalGainsResponse)(nil), // 1: trading.RunCapitalGainsResponse
	(*TaxDebtor)(nil),               // 2: trading.TaxDebtor
	(*ListTaxDebtsRequest)(nil),     // 3: trading.ListTaxDebtsRequest
	(*ListTaxDebtsResponse)(nil),    // 4: trading.ListTaxDebtsResponse
	(*GetMyTaxInfoRequest)(nil),     // 5: trading.GetMyTaxInfoRequest
	(*GetMyTaxInfoResponse)(nil),    // 6: trading.GetMyTaxInfoResponse
}
var file_trading_tax_proto_depIdxs = []int32{
	2, // 0: trading.ListTaxDebtsResponse.debtors:type_name -> trading.TaxDebtor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_trading_tax_proto_init() }
func file_trading_tax_proto_init() {
	if File_trading_tax_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_tax_proto_rawDesc), len(file_trading_tax_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trading_tax_proto_goTypes,
		DependencyIndexes: file_trading_tax_proto_depIdxs,
		MessageInfos:      file_trading_tax_proto_msgTypes,
	}.Build()
	File_trading_tax_proto = out.File
	file_trading_tax_proto_goTypes = nil
	file_trading_tax_proto_depIdxs = nil
}
