// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: user/totp.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Verify
type VerifyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCodeRequest) Reset() {
	*x = VerifyCodeRequest{}
	mi := &file_user_totp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeRequest) ProtoMessage() {}

func (x *VerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerifyCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCodeResponse) Reset() {
	*x = VerifyCodeResponse{}
	mi := &file_user_totp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeResponse) ProtoMessage() {}

func (x *VerifyCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeResponse.ProtoReflect.Descriptor instead.
func (*VerifyCodeResponse) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyCodeResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Enroll
type EnrollBeginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollBeginRequest) Reset() {
	*x = EnrollBeginRequest{}
	mi := &file_user_totp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollBeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollBeginRequest) ProtoMessage() {}

func (x *EnrollBeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollBeginRequest.ProtoReflect.Descriptor instead.
func (*EnrollBeginRequest) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{2}
}

func (x *EnrollBeginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EnrollBeginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollBeginResponse) Reset() {
	*x = EnrollBeginResponse{}
	mi := &file_user_totp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollBeginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollBeginResponse) ProtoMessage() {}

func (x *EnrollBeginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollBeginResponse.ProtoReflect.Descriptor instead.
func (*EnrollBeginResponse) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollBeginResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type EnrollConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollConfirmRequest) Reset() {
	*x = EnrollConfirmRequest{}
	mi := &file_user_totp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollConfirmRequest) ProtoMessage() {}

func (x *EnrollConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollConfirmRequest.ProtoReflect.Descriptor instead.
func (*EnrollConfirmRequest) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollConfirmRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EnrollConfirmRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type EnrollConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BackupCodes   []string               `protobuf:"bytes,2,rep,name=backup_codes,json=backupCodes,proto3" json:"backup_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollConfirmResponse) Reset() {
	*x = EnrollConfirmResponse{}
	mi := &file_user_totp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollConfirmResponse) ProtoMessage() {}

func (x *EnrollConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollConfirmResponse.ProtoReflect.Descriptor instead.
func (*EnrollConfirmResponse) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{5}
}

func (x *EnrollConfirmResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrollConfirmResponse) GetBackupCodes() []string {
	if x != nil {
		return x.BackupCodes
	}
	return nil
}

// Disable
type DisableBeginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableBeginRequest) Reset() {
	*x = DisableBeginRequest{}
	mi := &file_user_totp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableBeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableBeginRequest) ProtoMessage() {}

func (x *DisableBeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableBeginRequest.ProtoReflect.Descriptor instead.
func (*DisableBeginRequest) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{6}
}

func (x *DisableBeginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DisableBeginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableBeginResponse) Reset() {
	*x = DisableBeginResponse{}
	mi := &file_user_totp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableBeginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableBeginResponse) ProtoMessage() {}

func (x *DisableBeginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableBeginResponse.ProtoReflect.Descriptor instead.
func (*DisableBeginResponse) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{7}
}

func (x *DisableBeginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DisableConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableConfirmRequest) Reset() {
	*x = DisableConfirmRequest{}
	mi := &file_user_totp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableConfirmRequest) ProtoMessage() {}

func (x *DisableConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableConfirmRequest.ProtoReflect.Descriptor instead.
func (*DisableConfirmRequest) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{8}
}

func (x *DisableConfirmRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DisableConfirmRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DisableConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableConfirmResponse) Reset() {
	*x = DisableConfirmResponse{}
	mi := &file_user_totp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableConfirmResponse) ProtoMessage() {}

func (x *DisableConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableConfirmResponse.ProtoReflect.Descriptor instead.
func (*DisableConfirmResponse) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{9}
}

func (x *DisableConfirmResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Status
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_user_totp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{10}
}

func (x *StatusRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_user_totp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type TOTPStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TOTPStatusRequest) Reset() {
	*x = TOTPStatusRequest{}
	mi := &file_user_totp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOTPStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOTPStatusRequest) ProtoMessage() {}

func (x *TOTPStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOTPStatusRequest.ProtoReflect.Descriptor instead.
func (*TOTPStatusRequest) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{12}
}

func (x *TOTPStatusRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type TOTPStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TOTPStatusResponse) Reset() {
	*x = TOTPStatusResponse{}
	mi := &file_user_totp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOTPStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOTPStatusResponse) ProtoMessage() {}

func (x *TOTPStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_totp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOTPStatusResponse.ProtoReflect.Descriptor instead.
func (*TOTPStatusResponse) Descriptor() ([]byte, []int) {
	return file_user_totp_proto_rawDescGZIP(), []int{13}
}

func (x *TOTPStatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_user_totp_proto protoreflect.FileDescriptor

const file_user_totp_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/totp.proto\x12\x04user\"=\n" +
	"\x11VerifyCodeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"*\n" +
	"\x12VerifyCodeResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"*\n" +
	"\x12EnrollBeginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"'\n" +
	"\x13EnrollBeginResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"@\n" +
	"\x14EnrollConfirmRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"T\n" +
	"\x15EnrollConfirmResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fbackup_codes\x18\x02 \x03(\tR\vbackupCodes\"+\n" +
	"\x13DisableBeginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"0\n" +
	"\x14DisableBeginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\x15DisableConfirmRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"2\n" +
	"\x16DisableConfirmResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"%\n" +
	"\rStatusRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\")\n" +
	"\x11TOTPStatusRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\",\n" +
	"\x12TOTPStatusResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06activeB7Z5github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/userb\x06proto3"

var (
	file_user_totp_proto_rawDescOnce sync.Once
	file_user_totp_proto_rawDescData []byte
)

func file_user_totp_proto_rawDescGZIP() []byte {
	file_user_totp_proto_rawDescOnce.Do(func() {
		file_user_totp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_totp_proto_rawDesc), len(file_user_totp_proto_rawDesc)))
	})
	return file_user_totp_proto_rawDescData
}

var file_user_totp_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_user_totp_proto_goTypes = []any{
	(*VerifyCodeRequest)(nil),      // 0: user.VerifyCodeRequest
	(*VerifyCodeResponse)(nil),     // 1: user.VerifyCodeResponse
	(*EnrollBeginRequest)(nil),     // 2: user.EnrollBeginRequest
	(*EnrollBeginResponse)(nil),    // 3: user.EnrollBeginResponse
	(*EnrollConfirmRequest)(nil),   // 4: user.EnrollConfirmRequest
	(*EnrollConfirmResponse)(nil),  // 5: user.EnrollConfirmResponse
	(*DisableBeginRequest)(nil),    // 6: user.DisableBeginRequest
	(*DisableBeginResponse)(nil),   // 7: user.DisableBeginResponse
	(*DisableConfirmRequest)(nil),  // 8: user.DisableConfirmRequest
	(*DisableConfirmResponse)(nil), // 9: user.DisableConfirmResponse
	(*StatusRequest)(nil),          // 10: user.StatusRequest
	(*StatusResponse)(nil),         // 11: user.StatusResponse
	(*TOTPStatusRequest)(nil),      // 12: user.TOTPStatusRequest
	(*TOTPStatusResponse)(nil),     // 13: user.TOTPStatusResponse
}
var file_user_totp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_totp_proto_init() }
func file_user_totp_proto_init() {
	if File_user_totp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_totp_proto_rawDesc), len(file_user_totp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_totp_proto_goTypes,
		DependencyIndexes: file_user_totp_proto_depIdxs,
		MessageInfos:      file_user_totp_proto_msgTypes,
	}.Build()
	File_user_totp_proto = out.File
	file_user_totp_proto_goTypes = nil
	file_user_totp_proto_depIdxs = nil
}
