// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x04user\x1a\x0fuser/auth.proto\x1a\x11user/client.proto\x1a\x13user/employee.proto2\xe4\r\n" +
	"\vUserService\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x123\n" +
	"\x06Logout\x12\x13.user.LogoutRequest\x1a\x14.user.LogoutResponse\x126\n" +
	"\aRefresh\x12\x14.user.RefreshRequest\x1a\x15.user.RefreshResponse\x12N\n" +
	"\x13ValidateAccessToken\x12\x1a.user.ValidateTokenRequest\x1a\x1b.user.ValidateTokenResponse\x12O\n" +
	"\x14ValidateRefreshToken\x12\x1a.user.ValidateTokenRequest\x1a\x1b.user.ValidateTokenResponse\x12Q\n" +
	"\x14RequestPasswordReset\x12\x1b.user.PasswordActionRequest\x1a\x1c.user.PasswordActionResponse\x12V\n" +
	"\x19RequestInitialPasswordSet\x12\x1b.user.PasswordActionRequest\x1a\x1c.user.PasswordActionResponse\x12]\n" +
	"\x14SetPasswordWithToken\x12!.user.SetPasswordWithTokenRequest\x1a\".user.SetPasswordWithTokenResponse\x12W\n" +
	"\x12GetUserPermissions\x12\x1f.user.GetUserPermissionsRequest\x1a .user.GetUserPermissionsResponse\x12B\n" +
	"\rGetClientById\x12\x18.user.GetUserByIdRequest\x1a\x17.user.GetClientResponse\x12H\n" +
	"\x10GetClientByEmail\x12\x1b.user.GetUserByEmailRequest\x1a\x17.user.GetClientResponse\x12L\n" +
	"\x13CreateClientAccount\x12\x19.user.CreateClientRequest\x1a\x1a.user.CreateClientResponse\x12?\n" +
	"\n" +
	"GetClients\x12\x17.user.GetClientsRequest\x1a\x18.user.GetClientsResponse\x12E\n" +
	"\fUpdateClient\x12\x19.user.UpdateClientRequest\x1a\x1a.user.UpdateClientResponse\x12F\n" +
	"\x0fGetEmployeeById\x12\x18.user.GetUserByIdRequest\x1a\x19.user.GetEmployeeResponse\x12L\n" +
	"\x12GetEmployeeByEmail\x12\x1b.user.GetUserByEmailRequest\x1a\x19.user.GetEmployeeResponse\x12E\n" +
	"\fGetEmployees\x12\x19.user.GetEmployeesRequest\x1a\x1a.user.GetEmployeesResponse\x12H\n" +
	"\x0eUpdateEmployee\x12\x1b.user.UpdateEmployeeRequest\x1a\x19.user.GetEmployeeResponse\x12`\n" +
	"\x1aUpdateEmployeeTradingLimit\x12'.user.UpdateEmployeeTradingLimitRequest\x1a\x19.user.GetEmployeeResponse\x12`\n" +
	"\x1aUpdateEmployeeNeedApproval\x12'.user.UpdateEmployeeNeedApprovalRequest\x1a\x19.user.GetEmployeeResponse\x12E\n" +
	"\fGetActuaries\x12\x19.user.GetEmployeesRequest\x1a\x1a.user.GetEmployeesResponse\x12K\n" +
	"\x0eDeleteEmployee\x12\x1b.user.DeleteEmployeeRequest\x1a\x1c.user.DeleteEmployeeResponse\x12O\n" +
	"\x15CreateEmployeeAccount\x12\x1b.user.CreateEmployeeRequest\x1a\x19.user.GetEmployeeResponseB7Z5github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/userb\x06proto3"

var file_user_user_proto_goTypes = []any{
	(*LoginRequest)(nil),                      // 0: user.LoginRequest
	(*LogoutRequest)(nil),                     // 1: user.LogoutRequest
	(*RefreshRequest)(nil),                    // 2: user.RefreshRequest
	(*ValidateTokenRequest)(nil),              // 3: user.ValidateTokenRequest
	(*PasswordActionRequest)(nil),             // 4: user.PasswordActionRequest
	(*SetPasswordWithTokenRequest)(nil),       // 5: user.SetPasswordWithTokenRequest
	(*GetUserPermissionsRequest)(nil),         // 6: user.GetUserPermissionsRequest
	(*GetUserByIdRequest)(nil),                // 7: user.GetUserByIdRequest
	(*GetUserByEmailRequest)(nil),             // 8: user.GetUserByEmailRequest
	(*CreateClientRequest)(nil),               // 9: user.CreateClientRequest
	(*GetClientsRequest)(nil),                 // 10: user.GetClientsRequest
	(*UpdateClientRequest)(nil),               // 11: user.UpdateClientRequest
	(*GetEmployeesRequest)(nil),               // 12: user.GetEmployeesRequest
	(*UpdateEmployeeRequest)(nil),             // 13: user.UpdateEmployeeRequest
	(*UpdateEmployeeTradingLimitRequest)(nil), // 14: user.UpdateEmployeeTradingLimitRequest
	(*UpdateEmployeeNeedApprovalRequest)(nil), // 15: user.UpdateEmployeeNeedApprovalRequest
	(*DeleteEmployeeRequest)(nil),             // 16: user.DeleteEmployeeRequest
	(*CreateEmployeeRequest)(nil),             // 17: user.CreateEmployeeRequest
	(*LoginResponse)(nil),                     // 18: user.LoginResponse
	(*LogoutResponse)(nil),                    // 19: user.LogoutResponse
	(*RefreshResponse)(nil),                   // 20: user.RefreshResponse
	(*ValidateTokenResponse)(nil),             // 21: user.ValidateTokenResponse
	(*PasswordActionResponse)(nil),            // 22: user.PasswordActionResponse
	(*SetPasswordWithTokenResponse)(nil),      // 23: user.SetPasswordWithTokenResponse
	(*GetUserPermissionsResponse)(nil),        // 24: user.GetUserPermissionsResponse
	(*GetClientResponse)(nil),                 // 25: user.GetClientResponse
	(*CreateClientResponse)(nil),              // 26: user.CreateClientResponse
	(*GetClientsResponse)(nil),                // 27: user.GetClientsResponse
	(*UpdateClientResponse)(nil),              // 28: user.UpdateClientResponse
	(*GetEmployeeResponse)(nil),               // 29: user.GetEmployeeResponse
	(*GetEmployeesResponse)(nil),              // 30: user.GetEmployeesResponse
	(*DeleteEmployeeResponse)(nil),            // 31: user.DeleteEmployeeResponse
}
var file_user_user_proto_depIdxs = []int32{
	0,  // 0: user.UserService.Login:input_type -> user.LoginRequest
	1,  // 1: user.UserService.Logout:input_type -> user.LogoutRequest
	2,  // 2: user.UserService.Refresh:input_type -> user.RefreshRequest
	3,  // 3: user.UserService.ValidateAccessToken:input_type -> user.ValidateTokenRequest
	3,  // 4: user.UserService.ValidateRefreshToken:input_type -> user.ValidateTokenRequest
	4,  // 5: user.UserService.RequestPasswordReset:input_type -> user.PasswordActionRequest
	4,  // 6: user.UserService.RequestInitialPasswordSet:input_type -> user.PasswordActionRequest
	5,  // 7: user.UserService.SetPasswordWithToken:input_type -> user.SetPasswordWithTokenRequest
	6,  // 8: user.UserService.GetUserPermissions:input_type -> user.GetUserPermissionsRequest
	7,  // 9: user.UserService.GetClientById:input_type -> user.GetUserByIdRequest
	8,  // 10: user.UserService.GetClientByEmail:input_type -> user.GetUserByEmailRequest
	9,  // 11: user.UserService.CreateClientAccount:input_type -> user.CreateClientRequest
	10, // 12: user.UserService.GetClients:input_type -> user.GetClientsRequest
	11, // 13: user.UserService.UpdateClient:input_type -> user.UpdateClientRequest
	7,  // 14: user.UserService.GetEmployeeById:input_type -> user.GetUserByIdRequest
	8,  // 15: user.UserService.GetEmployeeByEmail:input_type -> user.GetUserByEmailRequest
	12, // 16: user.UserService.GetEmployees:input_type -> user.GetEmployeesRequest
	13, // 17: user.UserService.UpdateEmployee:input_type -> user.UpdateEmployeeRequest
	14, // 18: user.UserService.UpdateEmployeeTradingLimit:input_type -> user.UpdateEmployeeTradingLimitRequest
	15, // 19: user.UserService.UpdateEmployeeNeedApproval:input_type -> user.UpdateEmployeeNeedApprovalRequest
	12, // 20: user.UserService.GetActuaries:input_type -> user.GetEmployeesRequest
	16, // 21: user.UserService.DeleteEmployee:input_type -> user.DeleteEmployeeRequest
	17, // 22: user.UserService.CreateEmployeeAccount:input_type -> user.CreateEmployeeRequest
	18, // 23: user.UserService.Login:output_type -> user.LoginResponse
	19, // 24: user.UserService.Logout:output_type -> user.LogoutResponse
	20, // 25: user.UserService.Refresh:output_type -> user.RefreshResponse
	21, // 26: user.UserService.ValidateAccessToken:output_type -> user.ValidateTokenResponse
	21, // 27: user.UserService.ValidateRefreshToken:output_type -> user.ValidateTokenResponse
	22, // 28: user.UserService.RequestPasswordReset:output_type -> user.PasswordActionResponse
	22, // 29: user.UserService.RequestInitialPasswordSet:output_type -> user.PasswordActionResponse
	23, // 30: user.UserService.SetPasswordWithToken:output_type -> user.SetPasswordWithTokenResponse
	24, // 31: user.UserService.GetUserPermissions:output_type -> user.GetUserPermissionsResponse
	25, // 32: user.UserService.GetClientById:output_type -> user.GetClientResponse
	25, // 33: user.UserService.GetClientByEmail:output_type -> user.GetClientResponse
	26, // 34: user.UserService.CreateClientAccount:output_type -> user.CreateClientResponse
	27, // 35: user.UserService.GetClients:output_type -> user.GetClientsResponse
	28, // 36: user.UserService.UpdateClient:output_type -> user.UpdateClientResponse
	29, // 37: user.UserService.GetEmployeeById:output_type -> user.GetEmployeeResponse
	29, // 38: user.UserService.GetEmployeeByEmail:output_type -> user.GetEmployeeResponse
	30, // 39: user.UserService.GetEmployees:output_type -> user.GetEmployeesResponse
	29, // 40: user.UserService.UpdateEmployee:output_type -> user.GetEmployeeResponse
	29, // 41: user.UserService.UpdateEmployeeTradingLimit:output_type -> user.GetEmployeeResponse
	29, // 42: user.UserService.UpdateEmployeeNeedApproval:output_type -> user.GetEmployeeResponse
	30, // 43: user.UserService.GetActuaries:output_type -> user.GetEmployeesResponse
	31, // 44: user.UserService.DeleteEmployee:output_type -> user.DeleteEmployeeResponse
	29, // 45: user.UserService.CreateEmployeeAccount:output_type -> user.GetEmployeeResponse
	23, // [23:46] is the sub-list for method output_type
	0,  // [0:23] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	file_user_auth_proto_init()
	file_user_client_proto_init()
	file_user_employee_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
