// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: user/verification.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TOTPService_VerifyCode_FullMethodName     = "/user.TOTPService/VerifyCode"
	TOTPService_EnrollBegin_FullMethodName    = "/user.TOTPService/EnrollBegin"
	TOTPService_EnrollConfirm_FullMethodName  = "/user.TOTPService/EnrollConfirm"
	TOTPService_DisableBegin_FullMethodName   = "/user.TOTPService/DisableBegin"
	TOTPService_DisableConfirm_FullMethodName = "/user.TOTPService/DisableConfirm"
	TOTPService_Status_FullMethodName         = "/user.TOTPService/Status"
)

// TOTPServiceClient is the client API for TOTPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TOTPServiceClient interface {
	VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*VerifyCodeResponse, error)
	EnrollBegin(ctx context.Context, in *EnrollBeginRequest, opts ...grpc.CallOption) (*EnrollBeginResponse, error)
	EnrollConfirm(ctx context.Context, in *EnrollConfirmRequest, opts ...grpc.CallOption) (*EnrollConfirmResponse, error)
	DisableBegin(ctx context.Context, in *DisableBeginRequest, opts ...grpc.CallOption) (*DisableBeginResponse, error)
	DisableConfirm(ctx context.Context, in *DisableConfirmRequest, opts ...grpc.CallOption) (*DisableConfirmResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type tOTPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTOTPServiceClient(cc grpc.ClientConnInterface) TOTPServiceClient {
	return &tOTPServiceClient{cc}
}

func (c *tOTPServiceClient) VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*VerifyCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCodeResponse)
	err := c.cc.Invoke(ctx, TOTPService_VerifyCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tOTPServiceClient) EnrollBegin(ctx context.Context, in *EnrollBeginRequest, opts ...grpc.CallOption) (*EnrollBeginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollBeginResponse)
	err := c.cc.Invoke(ctx, TOTPService_EnrollBegin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tOTPServiceClient) EnrollConfirm(ctx context.Context, in *EnrollConfirmRequest, opts ...grpc.CallOption) (*EnrollConfirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollConfirmResponse)
	err := c.cc.Invoke(ctx, TOTPService_EnrollConfirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tOTPServiceClient) DisableBegin(ctx context.Context, in *DisableBeginRequest, opts ...grpc.CallOption) (*DisableBeginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableBeginResponse)
	err := c.cc.Invoke(ctx, TOTPService_DisableBegin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tOTPServiceClient) DisableConfirm(ctx context.Context, in *DisableConfirmRequest, opts ...grpc.CallOption) (*DisableConfirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableConfirmResponse)
	err := c.cc.Invoke(ctx, TOTPService_DisableConfirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tOTPServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TOTPService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TOTPServiceServer is the server API for TOTPService service.
// All implementations must embed UnimplementedTOTPServiceServer
// for forward compatibility.
type TOTPServiceServer interface {
	VerifyCode(context.Context, *VerifyCodeRequest) (*VerifyCodeResponse, error)
	EnrollBegin(context.Context, *EnrollBeginRequest) (*EnrollBeginResponse, error)
	EnrollConfirm(context.Context, *EnrollConfirmRequest) (*EnrollConfirmResponse, error)
	DisableBegin(context.Context, *DisableBeginRequest) (*DisableBeginResponse, error)
	DisableConfirm(context.Context, *DisableConfirmRequest) (*DisableConfirmResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedTOTPServiceServer()
}

// UnimplementedTOTPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTOTPServiceServer struct{}

func (UnimplementedTOTPServiceServer) VerifyCode(context.Context, *VerifyCodeRequest) (*VerifyCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyCode not implemented")
}
func (UnimplementedTOTPServiceServer) EnrollBegin(context.Context, *EnrollBeginRequest) (*EnrollBeginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollBegin not implemented")
}
func (UnimplementedTOTPServiceServer) EnrollConfirm(context.Context, *EnrollConfirmRequest) (*EnrollConfirmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollConfirm not implemented")
}
func (UnimplementedTOTPServiceServer) DisableBegin(context.Context, *DisableBeginRequest) (*DisableBeginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableBegin not implemented")
}
func (UnimplementedTOTPServiceServer) DisableConfirm(context.Context, *DisableConfirmRequest) (*DisableConfirmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableConfirm not implemented")
}
func (UnimplementedTOTPServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedTOTPServiceServer) mustEmbedUnimplementedTOTPServiceServer() {}
func (UnimplementedTOTPServiceServer) testEmbeddedByValue()                     {}

// UnsafeTOTPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TOTPServiceServer will
// result in compilation errors.
type UnsafeTOTPServiceServer interface {
	mustEmbedUnimplementedTOTPServiceServer()
}

func RegisterTOTPServiceServer(s grpc.ServiceRegistrar, srv TOTPServiceServer) {
	// If the following call panics, it indicates UnimplementedTOTPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TOTPService_ServiceDesc, srv)
}

func _TOTPService_VerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TOTPServiceServer).VerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TOTPService_VerifyCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TOTPServiceServer).VerifyCode(ctx, req.(*VerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TOTPService_EnrollBegin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollBeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TOTPServiceServer).EnrollBegin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TOTPService_EnrollBegin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TOTPServiceServer).EnrollBegin(ctx, req.(*EnrollBeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TOTPService_EnrollConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TOTPServiceServer).EnrollConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TOTPService_EnrollConfirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TOTPServiceServer).EnrollConfirm(ctx, req.(*EnrollConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TOTPService_DisableBegin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableBeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TOTPServiceServer).DisableBegin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TOTPService_DisableBegin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TOTPServiceServer).DisableBegin(ctx, req.(*DisableBeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TOTPService_DisableConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TOTPServiceServer).DisableConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TOTPService_DisableConfirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TOTPServiceServer).DisableConfirm(ctx, req.(*DisableConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TOTPService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TOTPServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TOTPService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TOTPServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TOTPService_ServiceDesc is the grpc.ServiceDesc for TOTPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TOTPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.TOTPService",
	HandlerType: (*TOTPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyCode",
			Handler:    _TOTPService_VerifyCode_Handler,
		},
		{
			MethodName: "EnrollBegin",
			Handler:    _TOTPService_EnrollBegin_Handler,
		},
		{
			MethodName: "EnrollConfirm",
			Handler:    _TOTPService_EnrollConfirm_Handler,
		},
		{
			MethodName: "DisableBegin",
			Handler:    _TOTPService_DisableBegin_Handler,
		},
		{
			MethodName: "DisableConfirm",
			Handler:    _TOTPService_DisableConfirm_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _TOTPService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/verification.proto",
}
