// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: bank/account.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber    string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountName      string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	OwnerId          int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Balance          float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,5,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	EmployeeId       int64                  `protobuf:"varint,6,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	CreationDate     int64                  `protobuf:"varint,7,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	ExpirationDate   int64                  `protobuf:"varint,8,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	Currency         string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	AccountType      string                 `protobuf:"bytes,11,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	DailyLimit       float64                `protobuf:"fixed64,12,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit     float64                `protobuf:"fixed64,13,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	DailySpending    float64                `protobuf:"fixed64,14,opt,name=daily_spending,json=dailySpending,proto3" json:"daily_spending,omitempty"`
	MonthlySpending  float64                `protobuf:"fixed64,15,opt,name=monthly_spending,json=monthlySpending,proto3" json:"monthly_spending,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_bank_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Account) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *Account) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Account) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *Account) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *Account) GetCreationDate() int64 {
	if x != nil {
		return x.CreationDate
	}
	return 0
}

func (x *Account) GetExpirationDate() int64 {
	if x != nil {
		return x.ExpirationDate
	}
	return 0
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Account) GetDailyLimit() float64 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

func (x *Account) GetMonthlyLimit() float64 {
	if x != nil {
		return x.MonthlyLimit
	}
	return 0
}

func (x *Account) GetDailySpending() float64 {
	if x != nil {
		return x.DailySpending
	}
	return 0
}

func (x *Account) GetMonthlySpending() float64 {
	if x != nil {
		return x.MonthlySpending
	}
	return 0
}

type BusinessInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CompanyName        string                 `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	RegistrationNumber string                 `protobuf:"bytes,2,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	Pib                string                 `protobuf:"bytes,3,opt,name=pib,proto3" json:"pib,omitempty"`
	ActivityCode       string                 `protobuf:"bytes,4,opt,name=activity_code,json=activityCode,proto3" json:"activity_code,omitempty"`
	Address            string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BusinessInfo) Reset() {
	*x = BusinessInfo{}
	mi := &file_bank_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessInfo) ProtoMessage() {}

func (x *BusinessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessInfo.ProtoReflect.Descriptor instead.
func (*BusinessInfo) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{1}
}

func (x *BusinessInfo) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *BusinessInfo) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *BusinessInfo) GetPib() string {
	if x != nil {
		return x.Pib
	}
	return ""
}

func (x *BusinessInfo) GetActivityCode() string {
	if x != nil {
		return x.ActivityCode
	}
	return ""
}

func (x *BusinessInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccountType    string                 `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Subtype        string                 `protobuf:"bytes,3,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	InitialBalance float64                `protobuf:"fixed64,5,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"`
	DailyLimit     float64                `protobuf:"fixed64,6,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit   float64                `protobuf:"fixed64,7,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	CreateCard     bool                   `protobuf:"varint,8,opt,name=create_card,json=createCard,proto3" json:"create_card,omitempty"`
	CardType       string                 `protobuf:"bytes,9,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardBrand      string                 `protobuf:"bytes,10,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	BusinessInfo   *BusinessInfo          `protobuf:"bytes,11,opt,name=business_info,json=businessInfo,proto3" json:"business_info,omitempty"`
	Name           string                 `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_bank_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreateAccountRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateAccountRequest) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *CreateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAccountRequest) GetInitialBalance() float64 {
	if x != nil {
		return x.InitialBalance
	}
	return 0
}

func (x *CreateAccountRequest) GetDailyLimit() float64 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

func (x *CreateAccountRequest) GetMonthlyLimit() float64 {
	if x != nil {
		return x.MonthlyLimit
	}
	return 0
}

func (x *CreateAccountRequest) GetCreateCard() bool {
	if x != nil {
		return x.CreateCard
	}
	return false
}

func (x *CreateAccountRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CreateAccountRequest) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

func (x *CreateAccountRequest) GetBusinessInfo() *BusinessInfo {
	if x != nil {
		return x.BusinessInfo
	}
	return nil
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateAccountResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber    string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountName      string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	OwnerId          int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Balance          float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,5,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	EmployeeId       int64                  `protobuf:"varint,6,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	CreationDate     string                 `protobuf:"bytes,7,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	ExpirationDate   string                 `protobuf:"bytes,8,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	Currency         string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	AccountType      string                 `protobuf:"bytes,11,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	DailyLimit       float64                `protobuf:"fixed64,12,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit     float64                `protobuf:"fixed64,13,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	DailySpending    float64                `protobuf:"fixed64,14,opt,name=daily_spending,json=dailySpending,proto3" json:"daily_spending,omitempty"`
	MonthlySpending  float64                `protobuf:"fixed64,15,opt,name=monthly_spending,json=monthlySpending,proto3" json:"monthly_spending,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_bank_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateAccountResponse) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *CreateAccountResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateAccountResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateAccountResponse) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *CreateAccountResponse) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CreateAccountResponse) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *CreateAccountResponse) GetExpirationDate() string {
	if x != nil {
		return x.ExpirationDate
	}
	return ""
}

func (x *CreateAccountResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateAccountResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateAccountResponse) GetDailyLimit() float64 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

func (x *CreateAccountResponse) GetMonthlyLimit() float64 {
	if x != nil {
		return x.MonthlyLimit
	}
	return 0
}

func (x *CreateAccountResponse) GetDailySpending() float64 {
	if x != nil {
		return x.DailySpending
	}
	return 0
}

func (x *CreateAccountResponse) GetMonthlySpending() float64 {
	if x != nil {
		return x.MonthlySpending
	}
	return 0
}

type UpdateAccountNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountNameRequest) Reset() {
	*x = UpdateAccountNameRequest{}
	mi := &file_bank_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountNameRequest) ProtoMessage() {}

func (x *UpdateAccountNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountNameRequest) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAccountNameRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *UpdateAccountNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateAccountNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountNameResponse) Reset() {
	*x = UpdateAccountNameResponse{}
	mi := &file_bank_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountNameResponse) ProtoMessage() {}

func (x *UpdateAccountNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountNameResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountNameResponse) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{5}
}

type UpdateAccountLimitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	DailyLimit    *int64                 `protobuf:"varint,2,opt,name=daily_limit,json=dailyLimit,proto3,oneof" json:"daily_limit,omitempty"`
	MonthlyLimit  *int64                 `protobuf:"varint,3,opt,name=monthly_limit,json=monthlyLimit,proto3,oneof" json:"monthly_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountLimitsRequest) Reset() {
	*x = UpdateAccountLimitsRequest{}
	mi := &file_bank_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountLimitsRequest) ProtoMessage() {}

func (x *UpdateAccountLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountLimitsRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountLimitsRequest) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccountLimitsRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *UpdateAccountLimitsRequest) GetDailyLimit() int64 {
	if x != nil && x.DailyLimit != nil {
		return *x.DailyLimit
	}
	return 0
}

func (x *UpdateAccountLimitsRequest) GetMonthlyLimit() int64 {
	if x != nil && x.MonthlyLimit != nil {
		return *x.MonthlyLimit
	}
	return 0
}

type UpdateAccountLimitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountLimitsResponse) Reset() {
	*x = UpdateAccountLimitsResponse{}
	mi := &file_bank_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountLimitsResponse) ProtoMessage() {}

func (x *UpdateAccountLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountLimitsResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountLimitsResponse) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{7}
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	AccountNumber string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_bank_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{8}
}

func (x *ListAccountsRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ListAccountsRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ListAccountsRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_bank_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{9}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type GetAccountDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountDetailsRequest) Reset() {
	*x = GetAccountDetailsRequest{}
	mi := &file_bank_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountDetailsRequest) ProtoMessage() {}

func (x *GetAccountDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetAccountDetailsRequest) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{10}
}

func (x *GetAccountDetailsRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type GetAccountDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountDetailsResponse) Reset() {
	*x = GetAccountDetailsResponse{}
	mi := &file_bank_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountDetailsResponse) ProtoMessage() {}

func (x *GetAccountDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetAccountDetailsResponse) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{11}
}

func (x *GetAccountDetailsResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type ClientTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromAccount     string                 `protobuf:"bytes,1,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount       string                 `protobuf:"bytes,2,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	InitialAmount   float64                `protobuf:"fixed64,3,opt,name=initial_amount,json=initialAmount,proto3" json:"initial_amount,omitempty"`
	FinalAmount     float64                `protobuf:"fixed64,4,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	Fee             float64                `protobuf:"fixed64,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentCode     string                 `protobuf:"bytes,7,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,8,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Purpose         string                 `protobuf:"bytes,9,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp       int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientTransaction) Reset() {
	*x = ClientTransaction{}
	mi := &file_bank_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTransaction) ProtoMessage() {}

func (x *ClientTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTransaction.ProtoReflect.Descriptor instead.
func (*ClientTransaction) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{12}
}

func (x *ClientTransaction) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *ClientTransaction) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *ClientTransaction) GetInitialAmount() float64 {
	if x != nil {
		return x.InitialAmount
	}
	return 0
}

func (x *ClientTransaction) GetFinalAmount() float64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *ClientTransaction) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *ClientTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ClientTransaction) GetPaymentCode() string {
	if x != nil {
		return x.PaymentCode
	}
	return ""
}

func (x *ClientTransaction) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *ClientTransaction) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ClientTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClientTransaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ListClientTranasctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientTranasctionsRequest) Reset() {
	*x = ListClientTranasctionsRequest{}
	mi := &file_bank_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientTranasctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientTranasctionsRequest) ProtoMessage() {}

func (x *ListClientTranasctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientTranasctionsRequest.ProtoReflect.Descriptor instead.
func (*ListClientTranasctionsRequest) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{13}
}

func (x *ListClientTranasctionsRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *ListClientTranasctionsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListClientTranasctionsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ListClientTranasctionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListClientTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*ClientTransaction   `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientTransactionsResponse) Reset() {
	*x = ListClientTransactionsResponse{}
	mi := &file_bank_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientTransactionsResponse) ProtoMessage() {}

func (x *ListClientTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListClientTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_bank_account_proto_rawDescGZIP(), []int{14}
}

func (x *ListClientTransactionsResponse) GetTransactions() []*ClientTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_bank_account_proto protoreflect.FileDescriptor

const file_bank_account_proto_rawDesc = "" +
	"\n" +
	"\x12bank/account.proto\x12\x04bank\"\x93\x04\n" +
	"\aAccount\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\x12+\n" +
	"\x11available_balance\x18\x05 \x01(\x01R\x10availableBalance\x12\x1f\n" +
	"\vemployee_id\x18\x06 \x01(\x03R\n" +
	"employeeId\x12#\n" +
	"\rcreation_date\x18\a \x01(\x03R\fcreationDate\x12'\n" +
	"\x0fexpiration_date\x18\b \x01(\x03R\x0eexpirationDate\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12!\n" +
	"\faccount_type\x18\v \x01(\tR\vaccountType\x12\x1f\n" +
	"\vdaily_limit\x18\f \x01(\x01R\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\r \x01(\x01R\fmonthlyLimit\x12%\n" +
	"\x0edaily_spending\x18\x0e \x01(\x01R\rdailySpending\x12)\n" +
	"\x10monthly_spending\x18\x0f \x01(\x01R\x0fmonthlySpending\"\xb3\x01\n" +
	"\fBusinessInfo\x12!\n" +
	"\fcompany_name\x18\x01 \x01(\tR\vcompanyName\x12/\n" +
	"\x13registration_number\x18\x02 \x01(\tR\x12registrationNumber\x12\x10\n" +
	"\x03pib\x18\x03 \x01(\tR\x03pib\x12#\n" +
	"\ractivity_code\x18\x04 \x01(\tR\factivityCode\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\"\xa5\x03\n" +
	"\x14CreateAccountRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\x12!\n" +
	"\faccount_type\x18\x02 \x01(\tR\vaccountType\x12\x18\n" +
	"\asubtype\x18\x03 \x01(\tR\asubtype\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12'\n" +
	"\x0finitial_balance\x18\x05 \x01(\x01R\x0einitialBalance\x12\x1f\n" +
	"\vdaily_limit\x18\x06 \x01(\x01R\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\a \x01(\x01R\fmonthlyLimit\x12\x1f\n" +
	"\vcreate_card\x18\b \x01(\bR\n" +
	"createCard\x12\x1b\n" +
	"\tcard_type\x18\t \x01(\tR\bcardType\x12\x1d\n" +
	"\n" +
	"card_brand\x18\n" +
	" \x01(\tR\tcardBrand\x127\n" +
	"\rbusiness_info\x18\v \x01(\v2\x12.bank.BusinessInfoR\fbusinessInfo\x12\x12\n" +
	"\x04name\x18\f \x01(\tR\x04name\"\xa1\x04\n" +
	"\x15CreateAccountResponse\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\x12+\n" +
	"\x11available_balance\x18\x05 \x01(\x01R\x10availableBalance\x12\x1f\n" +
	"\vemployee_id\x18\x06 \x01(\x03R\n" +
	"employeeId\x12#\n" +
	"\rcreation_date\x18\a \x01(\tR\fcreationDate\x12'\n" +
	"\x0fexpiration_date\x18\b \x01(\tR\x0eexpirationDate\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12!\n" +
	"\faccount_type\x18\v \x01(\tR\vaccountType\x12\x1f\n" +
	"\vdaily_limit\x18\f \x01(\x01R\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\r \x01(\x01R\fmonthlyLimit\x12%\n" +
	"\x0edaily_spending\x18\x0e \x01(\x01R\rdailySpending\x12)\n" +
	"\x10monthly_spending\x18\x0f \x01(\x01R\x0fmonthlySpending\"U\n" +
	"\x18UpdateAccountNameRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1b\n" +
	"\x19UpdateAccountNameResponse\"\xb5\x01\n" +
	"\x1aUpdateAccountLimitsRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12$\n" +
	"\vdaily_limit\x18\x02 \x01(\x03H\x00R\n" +
	"dailyLimit\x88\x01\x01\x12(\n" +
	"\rmonthly_limit\x18\x03 \x01(\x03H\x01R\fmonthlyLimit\x88\x01\x01B\x0e\n" +
	"\f_daily_limitB\x10\n" +
	"\x0e_monthly_limit\"\x1d\n" +
	"\x1bUpdateAccountLimitsResponse\"v\n" +
	"\x13ListAccountsRequest\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\"A\n" +
	"\x14ListAccountsResponse\x12)\n" +
	"\baccounts\x18\x01 \x03(\v2\r.bank.AccountR\baccounts\"@\n" +
	"\x18GetAccountDetailsRequest\x12$\n" +
	"\raccountNumber\x18\x01 \x01(\tR\raccountNumber\"D\n" +
	"\x19GetAccountDetailsResponse\x12'\n" +
	"\aaccount\x18\x01 \x01(\v2\r.bank.AccountR\aaccount\"\xeb\x02\n" +
	"\x11ClientTransaction\x12!\n" +
	"\ffrom_account\x18\x01 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x02 \x01(\tR\ttoAccount\x12%\n" +
	"\x0einitial_amount\x18\x03 \x01(\x01R\rinitialAmount\x12!\n" +
	"\ffinal_amount\x18\x04 \x01(\x01R\vfinalAmount\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x01R\x03fee\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12!\n" +
	"\fpayment_code\x18\a \x01(\tR\vpaymentCode\x12)\n" +
	"\x10reference_number\x18\b \x01(\tR\x0freferenceNumber\x12\x18\n" +
	"\apurpose\x18\t \x01(\tR\apurpose\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\"\x8a\x01\n" +
	"\x1dListClientTranasctionsRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"]\n" +
	"\x1eListClientTransactionsResponse\x12;\n" +
	"\ftransactions\x18\x01 \x03(\v2\x17.bank.ClientTransactionR\ftransactionsB7Z5github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/bankb\x06proto3"

var (
	file_bank_account_proto_rawDescOnce sync.Once
	file_bank_account_proto_rawDescData []byte
)

func file_bank_account_proto_rawDescGZIP() []byte {
	file_bank_account_proto_rawDescOnce.Do(func() {
		file_bank_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bank_account_proto_rawDesc), len(file_bank_account_proto_rawDesc)))
	})
	return file_bank_account_proto_rawDescData
}

var file_bank_account_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_bank_account_proto_goTypes = []any{
	(*Account)(nil),                        // 0: bank.Account
	(*BusinessInfo)(nil),                   // 1: bank.BusinessInfo
	(*CreateAccountRequest)(nil),           // 2: bank.CreateAccountRequest
	(*CreateAccountResponse)(nil),          // 3: bank.CreateAccountResponse
	(*UpdateAccountNameRequest)(nil),       // 4: bank.UpdateAccountNameRequest
	(*UpdateAccountNameResponse)(nil),      // 5: bank.UpdateAccountNameResponse
	(*UpdateAccountLimitsRequest)(nil),     // 6: bank.UpdateAccountLimitsRequest
	(*UpdateAccountLimitsResponse)(nil),    // 7: bank.UpdateAccountLimitsResponse
	(*ListAccountsRequest)(nil),            // 8: bank.ListAccountsRequest
	(*ListAccountsResponse)(nil),           // 9: bank.ListAccountsResponse
	(*GetAccountDetailsRequest)(nil),       // 10: bank.GetAccountDetailsRequest
	(*GetAccountDetailsResponse)(nil),      // 11: bank.GetAccountDetailsResponse
	(*ClientTransaction)(nil),              // 12: bank.ClientTransaction
	(*ListClientTranasctionsRequest)(nil),  // 13: bank.ListClientTranasctionsRequest
	(*ListClientTransactionsResponse)(nil), // 14: bank.ListClientTransactionsResponse
}
var file_bank_account_proto_depIdxs = []int32{
	1,  // 0: bank.CreateAccountRequest.business_info:type_name -> bank.BusinessInfo
	0,  // 1: bank.ListAccountsResponse.accounts:type_name -> bank.Account
	0,  // 2: bank.GetAccountDetailsResponse.account:type_name -> bank.Account
	12, // 3: bank.ListClientTransactionsResponse.transactions:type_name -> bank.ClientTransaction
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_bank_account_proto_init() }
func file_bank_account_proto_init() {
	if File_bank_account_proto != nil {
		return
	}
	file_bank_account_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_account_proto_rawDesc), len(file_bank_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bank_account_proto_goTypes,
		DependencyIndexes: file_bank_account_proto_depIdxs,
		MessageInfos:      file_bank_account_proto_msgTypes,
	}.Build()
	File_bank_account_proto = out.File
	file_bank_account_proto_goTypes = nil
	file_bank_account_proto_depIdxs = nil
}
