// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: bank/bank.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_bank_bank_proto protoreflect.FileDescriptor

const file_bank_bank_proto_rawDesc = "" +
	"\n" +
	"\x0fbank/bank.proto\x12\x04bank\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12bank/account.proto\x1a\x0fbank/card.proto\x1a\x12bank/company.proto\x1a\x0fbank/loan.proto\x1a\x14bank/recipient.proto\x1a\x16bank/transaction.proto2\xf7\x14\n" +
	"\vBankService\x12H\n" +
	"\rCreateCompany\x12\x1a.bank.CreateCompanyRequest\x1a\x1b.bank.CreateCompanyResponse\x12K\n" +
	"\x0eGetCompanyById\x12\x1b.bank.GetCompanyByIdRequest\x1a\x1c.bank.GetCompanyByIdResponse\x12E\n" +
	"\fGetCompanies\x12\x19.bank.GetCompaniesRequest\x1a\x1a.bank.GetCompaniesResponse\x12H\n" +
	"\rUpdateCompany\x12\x1a.bank.UpdateCompanyRequest\x1a\x1b.bank.UpdateCompanyResponse\x12H\n" +
	"\rCreateAccount\x12\x1a.bank.CreateAccountRequest\x1a\x1b.bank.CreateAccountResponse\x12T\n" +
	"\x11UpdateAccountName\x12\x1e.bank.UpdateAccountNameRequest\x1a\x1f.bank.UpdateAccountNameResponse\x12Z\n" +
	"\x13UpdateAccountLimits\x12 .bank.UpdateAccountLimitsRequest\x1a!.bank.UpdateAccountLimitsResponse\x12E\n" +
	"\fListAccounts\x12\x19.bank.ListAccountsRequest\x1a\x1a.bank.ListAccountsResponse\x12T\n" +
	"\x11GetAccountDetails\x12\x1e.bank.GetAccountDetailsRequest\x1a\x1f.bank.GetAccountDetailsResponse\x12c\n" +
	"\x16ListClientTransactions\x12#.bank.ListClientTranasctionsRequest\x1a$.bank.ListClientTransactionsResponse\x129\n" +
	"\n" +
	"CreateCard\x12\x17.bank.CreateCardRequest\x1a\x12.bank.CardResponse\x12B\n" +
	"\vRequestCard\x12\x18.bank.RequestCardRequest\x1a\x19.bank.RequestCardResponse\x12B\n" +
	"\vConfirmCard\x12\x18.bank.ConfirmCardRequest\x1a\x19.bank.ConfirmCardResponse\x129\n" +
	"\bGetCards\x12\x15.bank.GetCardsRequest\x1a\x16.bank.GetCardsResponse\x12<\n" +
	"\tBlockCard\x12\x16.bank.BlockCardRequest\x1a\x17.bank.BlockCardResponse\x129\n" +
	"\bGetLoans\x12\x15.bank.GetLoansRequest\x1a\x16.bank.GetLoansResponse\x12;\n" +
	"\x0fGetLoanByNumber\x12\x1c.bank.GetLoanByNumberRequest\x1a\n" +
	".bank.Loan\x12T\n" +
	"\x11CreateLoanRequest\x12\x1e.bank.CreateLoanRequestRequest\x1a\x1f.bank.CreateLoanRequestResponse\x12N\n" +
	"\x0fGetLoanRequests\x12\x1c.bank.GetLoanRequestsRequest\x1a\x1d.bank.GetLoanRequestsResponse\x12W\n" +
	"\x12ApproveLoanRequest\x12\x1f.bank.ApproveLoanRequestRequest\x1a .bank.ApproveLoanRequestResponse\x12T\n" +
	"\x11RejectLoanRequest\x12\x1e.bank.RejectLoanRequestRequest\x1a\x1f.bank.RejectLoanRequestResponse\x12?\n" +
	"\vGetAllLoans\x12\x18.bank.GetAllLoansRequest\x1a\x16.bank.GetLoansResponse\x12]\n" +
	"\x14GetPaymentRecipients\x12!.bank.GetPaymentRecipientsRequest\x1a\".bank.GetPaymentRecipientsResponse\x12c\n" +
	"\x16CreatePaymentRecipient\x12#.bank.CreatePaymentRecipientRequest\x1a$.bank.CreatePaymentRecipientResponse\x12c\n" +
	"\x16UpdatePaymentRecipient\x12#.bank.UpdatePaymentRecipientRequest\x1a$.bank.UpdatePaymentRecipientResponse\x12c\n" +
	"\x16DeletePaymentRecipient\x12#.bank.DeletePaymentRecipientRequest\x1a$.bank.DeletePaymentRecipientResponse\x12N\n" +
	"\x0fGetTransactions\x12\x1c.bank.GetTransactionsRequest\x1a\x1d.bank.GetTransactionsResponse\x12W\n" +
	"\x12GetTransactionById\x12\x1f.bank.GetTransactionByIdRequest\x1a .bank.GetTransactionByIdResponse\x12c\n" +
	"\x16GenerateTransactionPdf\x12#.bank.GenerateTransactionPdfRequest\x1a$.bank.GenerateTransactionPdfResponse\x12M\n" +
	"\x1cTransferMoneyBetweenAccounts\x12\x15.bank.TransferRequest\x1a\x16.bank.TransferResponse\x12H\n" +
	"\x19PayoutMoneyToOtherAccount\x12\x14.bank.PaymentRequest\x1a\x15.bank.PaymentResponse\x12^\n" +
	"\x1fGetTransfersHistoryForUserEmail\x12\x1c.bank.TransferHistoryRequest\x1a\x1d.bank.TransferHistoryResponse\x12c\n" +
	"\x16AuthorizeAccountAccess\x12#.bank.AuthorizeAccountAccessRequest\x1a$.bank.AuthorizeAccountAccessResponseB7Z5github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/bankb\x06proto3"

var file_bank_bank_proto_goTypes = []any{
	(*CreateCompanyRequest)(nil),           // 0: bank.CreateCompanyRequest
	(*GetCompanyByIdRequest)(nil),          // 1: bank.GetCompanyByIdRequest
	(*GetCompaniesRequest)(nil),            // 2: bank.GetCompaniesRequest
	(*UpdateCompanyRequest)(nil),           // 3: bank.UpdateCompanyRequest
	(*CreateAccountRequest)(nil),           // 4: bank.CreateAccountRequest
	(*UpdateAccountNameRequest)(nil),       // 5: bank.UpdateAccountNameRequest
	(*UpdateAccountLimitsRequest)(nil),     // 6: bank.UpdateAccountLimitsRequest
	(*ListAccountsRequest)(nil),            // 7: bank.ListAccountsRequest
	(*GetAccountDetailsRequest)(nil),       // 8: bank.GetAccountDetailsRequest
	(*ListClientTranasctionsRequest)(nil),  // 9: bank.ListClientTranasctionsRequest
	(*CreateCardRequest)(nil),              // 10: bank.CreateCardRequest
	(*RequestCardRequest)(nil),             // 11: bank.RequestCardRequest
	(*ConfirmCardRequest)(nil),             // 12: bank.ConfirmCardRequest
	(*GetCardsRequest)(nil),                // 13: bank.GetCardsRequest
	(*BlockCardRequest)(nil),               // 14: bank.BlockCardRequest
	(*GetLoansRequest)(nil),                // 15: bank.GetLoansRequest
	(*GetLoanByNumberRequest)(nil),         // 16: bank.GetLoanByNumberRequest
	(*CreateLoanRequestRequest)(nil),       // 17: bank.CreateLoanRequestRequest
	(*GetLoanRequestsRequest)(nil),         // 18: bank.GetLoanRequestsRequest
	(*ApproveLoanRequestRequest)(nil),      // 19: bank.ApproveLoanRequestRequest
	(*RejectLoanRequestRequest)(nil),       // 20: bank.RejectLoanRequestRequest
	(*GetAllLoansRequest)(nil),             // 21: bank.GetAllLoansRequest
	(*GetPaymentRecipientsRequest)(nil),    // 22: bank.GetPaymentRecipientsRequest
	(*CreatePaymentRecipientRequest)(nil),  // 23: bank.CreatePaymentRecipientRequest
	(*UpdatePaymentRecipientRequest)(nil),  // 24: bank.UpdatePaymentRecipientRequest
	(*DeletePaymentRecipientRequest)(nil),  // 25: bank.DeletePaymentRecipientRequest
	(*GetTransactionsRequest)(nil),         // 26: bank.GetTransactionsRequest
	(*GetTransactionByIdRequest)(nil),      // 27: bank.GetTransactionByIdRequest
	(*GenerateTransactionPdfRequest)(nil),  // 28: bank.GenerateTransactionPdfRequest
	(*TransferRequest)(nil),                // 29: bank.TransferRequest
	(*PaymentRequest)(nil),                 // 30: bank.PaymentRequest
	(*TransferHistoryRequest)(nil),         // 31: bank.TransferHistoryRequest
	(*AuthorizeAccountAccessRequest)(nil),  // 32: bank.AuthorizeAccountAccessRequest
	(*CreateCompanyResponse)(nil),          // 33: bank.CreateCompanyResponse
	(*GetCompanyByIdResponse)(nil),         // 34: bank.GetCompanyByIdResponse
	(*GetCompaniesResponse)(nil),           // 35: bank.GetCompaniesResponse
	(*UpdateCompanyResponse)(nil),          // 36: bank.UpdateCompanyResponse
	(*CreateAccountResponse)(nil),          // 37: bank.CreateAccountResponse
	(*UpdateAccountNameResponse)(nil),      // 38: bank.UpdateAccountNameResponse
	(*UpdateAccountLimitsResponse)(nil),    // 39: bank.UpdateAccountLimitsResponse
	(*ListAccountsResponse)(nil),           // 40: bank.ListAccountsResponse
	(*GetAccountDetailsResponse)(nil),      // 41: bank.GetAccountDetailsResponse
	(*ListClientTransactionsResponse)(nil), // 42: bank.ListClientTransactionsResponse
	(*CardResponse)(nil),                   // 43: bank.CardResponse
	(*RequestCardResponse)(nil),            // 44: bank.RequestCardResponse
	(*ConfirmCardResponse)(nil),            // 45: bank.ConfirmCardResponse
	(*GetCardsResponse)(nil),               // 46: bank.GetCardsResponse
	(*BlockCardResponse)(nil),              // 47: bank.BlockCardResponse
	(*GetLoansResponse)(nil),               // 48: bank.GetLoansResponse
	(*Loan)(nil),                           // 49: bank.Loan
	(*CreateLoanRequestResponse)(nil),      // 50: bank.CreateLoanRequestResponse
	(*GetLoanRequestsResponse)(nil),        // 51: bank.GetLoanRequestsResponse
	(*ApproveLoanRequestResponse)(nil),     // 52: bank.ApproveLoanRequestResponse
	(*RejectLoanRequestResponse)(nil),      // 53: bank.RejectLoanRequestResponse
	(*GetPaymentRecipientsResponse)(nil),   // 54: bank.GetPaymentRecipientsResponse
	(*CreatePaymentRecipientResponse)(nil), // 55: bank.CreatePaymentRecipientResponse
	(*UpdatePaymentRecipientResponse)(nil), // 56: bank.UpdatePaymentRecipientResponse
	(*DeletePaymentRecipientResponse)(nil), // 57: bank.DeletePaymentRecipientResponse
	(*GetTransactionsResponse)(nil),        // 58: bank.GetTransactionsResponse
	(*GetTransactionByIdResponse)(nil),     // 59: bank.GetTransactionByIdResponse
	(*GenerateTransactionPdfResponse)(nil), // 60: bank.GenerateTransactionPdfResponse
	(*TransferResponse)(nil),               // 61: bank.TransferResponse
	(*PaymentResponse)(nil),                // 62: bank.PaymentResponse
	(*TransferHistoryResponse)(nil),        // 63: bank.TransferHistoryResponse
	(*AuthorizeAccountAccessResponse)(nil), // 64: bank.AuthorizeAccountAccessResponse
}
var file_bank_bank_proto_depIdxs = []int32{
	0,  // 0: bank.BankService.CreateCompany:input_type -> bank.CreateCompanyRequest
	1,  // 1: bank.BankService.GetCompanyById:input_type -> bank.GetCompanyByIdRequest
	2,  // 2: bank.BankService.GetCompanies:input_type -> bank.GetCompaniesRequest
	3,  // 3: bank.BankService.UpdateCompany:input_type -> bank.UpdateCompanyRequest
	4,  // 4: bank.BankService.CreateAccount:input_type -> bank.CreateAccountRequest
	5,  // 5: bank.BankService.UpdateAccountName:input_type -> bank.UpdateAccountNameRequest
	6,  // 6: bank.BankService.UpdateAccountLimits:input_type -> bank.UpdateAccountLimitsRequest
	7,  // 7: bank.BankService.ListAccounts:input_type -> bank.ListAccountsRequest
	8,  // 8: bank.BankService.GetAccountDetails:input_type -> bank.GetAccountDetailsRequest
	9,  // 9: bank.BankService.ListClientTransactions:input_type -> bank.ListClientTranasctionsRequest
	10, // 10: bank.BankService.CreateCard:input_type -> bank.CreateCardRequest
	11, // 11: bank.BankService.RequestCard:input_type -> bank.RequestCardRequest
	12, // 12: bank.BankService.ConfirmCard:input_type -> bank.ConfirmCardRequest
	13, // 13: bank.BankService.GetCards:input_type -> bank.GetCardsRequest
	14, // 14: bank.BankService.BlockCard:input_type -> bank.BlockCardRequest
	15, // 15: bank.BankService.GetLoans:input_type -> bank.GetLoansRequest
	16, // 16: bank.BankService.GetLoanByNumber:input_type -> bank.GetLoanByNumberRequest
	17, // 17: bank.BankService.CreateLoanRequest:input_type -> bank.CreateLoanRequestRequest
	18, // 18: bank.BankService.GetLoanRequests:input_type -> bank.GetLoanRequestsRequest
	19, // 19: bank.BankService.ApproveLoanRequest:input_type -> bank.ApproveLoanRequestRequest
	20, // 20: bank.BankService.RejectLoanRequest:input_type -> bank.RejectLoanRequestRequest
	21, // 21: bank.BankService.GetAllLoans:input_type -> bank.GetAllLoansRequest
	22, // 22: bank.BankService.GetPaymentRecipients:input_type -> bank.GetPaymentRecipientsRequest
	23, // 23: bank.BankService.CreatePaymentRecipient:input_type -> bank.CreatePaymentRecipientRequest
	24, // 24: bank.BankService.UpdatePaymentRecipient:input_type -> bank.UpdatePaymentRecipientRequest
	25, // 25: bank.BankService.DeletePaymentRecipient:input_type -> bank.DeletePaymentRecipientRequest
	26, // 26: bank.BankService.GetTransactions:input_type -> bank.GetTransactionsRequest
	27, // 27: bank.BankService.GetTransactionById:input_type -> bank.GetTransactionByIdRequest
	28, // 28: bank.BankService.GenerateTransactionPdf:input_type -> bank.GenerateTransactionPdfRequest
	29, // 29: bank.BankService.TransferMoneyBetweenAccounts:input_type -> bank.TransferRequest
	30, // 30: bank.BankService.PayoutMoneyToOtherAccount:input_type -> bank.PaymentRequest
	31, // 31: bank.BankService.GetTransfersHistoryForUserEmail:input_type -> bank.TransferHistoryRequest
	32, // 32: bank.BankService.AuthorizeAccountAccess:input_type -> bank.AuthorizeAccountAccessRequest
	33, // 33: bank.BankService.CreateCompany:output_type -> bank.CreateCompanyResponse
	34, // 34: bank.BankService.GetCompanyById:output_type -> bank.GetCompanyByIdResponse
	35, // 35: bank.BankService.GetCompanies:output_type -> bank.GetCompaniesResponse
	36, // 36: bank.BankService.UpdateCompany:output_type -> bank.UpdateCompanyResponse
	37, // 37: bank.BankService.CreateAccount:output_type -> bank.CreateAccountResponse
	38, // 38: bank.BankService.UpdateAccountName:output_type -> bank.UpdateAccountNameResponse
	39, // 39: bank.BankService.UpdateAccountLimits:output_type -> bank.UpdateAccountLimitsResponse
	40, // 40: bank.BankService.ListAccounts:output_type -> bank.ListAccountsResponse
	41, // 41: bank.BankService.GetAccountDetails:output_type -> bank.GetAccountDetailsResponse
	42, // 42: bank.BankService.ListClientTransactions:output_type -> bank.ListClientTransactionsResponse
	43, // 43: bank.BankService.CreateCard:output_type -> bank.CardResponse
	44, // 44: bank.BankService.RequestCard:output_type -> bank.RequestCardResponse
	45, // 45: bank.BankService.ConfirmCard:output_type -> bank.ConfirmCardResponse
	46, // 46: bank.BankService.GetCards:output_type -> bank.GetCardsResponse
	47, // 47: bank.BankService.BlockCard:output_type -> bank.BlockCardResponse
	48, // 48: bank.BankService.GetLoans:output_type -> bank.GetLoansResponse
	49, // 49: bank.BankService.GetLoanByNumber:output_type -> bank.Loan
	50, // 50: bank.BankService.CreateLoanRequest:output_type -> bank.CreateLoanRequestResponse
	51, // 51: bank.BankService.GetLoanRequests:output_type -> bank.GetLoanRequestsResponse
	52, // 52: bank.BankService.ApproveLoanRequest:output_type -> bank.ApproveLoanRequestResponse
	53, // 53: bank.BankService.RejectLoanRequest:output_type -> bank.RejectLoanRequestResponse
	48, // 54: bank.BankService.GetAllLoans:output_type -> bank.GetLoansResponse
	54, // 55: bank.BankService.GetPaymentRecipients:output_type -> bank.GetPaymentRecipientsResponse
	55, // 56: bank.BankService.CreatePaymentRecipient:output_type -> bank.CreatePaymentRecipientResponse
	56, // 57: bank.BankService.UpdatePaymentRecipient:output_type -> bank.UpdatePaymentRecipientResponse
	57, // 58: bank.BankService.DeletePaymentRecipient:output_type -> bank.DeletePaymentRecipientResponse
	58, // 59: bank.BankService.GetTransactions:output_type -> bank.GetTransactionsResponse
	59, // 60: bank.BankService.GetTransactionById:output_type -> bank.GetTransactionByIdResponse
	60, // 61: bank.BankService.GenerateTransactionPdf:output_type -> bank.GenerateTransactionPdfResponse
	61, // 62: bank.BankService.TransferMoneyBetweenAccounts:output_type -> bank.TransferResponse
	62, // 63: bank.BankService.PayoutMoneyToOtherAccount:output_type -> bank.PaymentResponse
	63, // 64: bank.BankService.GetTransfersHistoryForUserEmail:output_type -> bank.TransferHistoryResponse
	64, // 65: bank.BankService.AuthorizeAccountAccess:output_type -> bank.AuthorizeAccountAccessResponse
	33, // [33:66] is the sub-list for method output_type
	0,  // [0:33] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_bank_bank_proto_init() }
func file_bank_bank_proto_init() {
	if File_bank_bank_proto != nil {
		return
	}
	file_bank_account_proto_init()
	file_bank_card_proto_init()
	file_bank_company_proto_init()
	file_bank_loan_proto_init()
	file_bank_recipient_proto_init()
	file_bank_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_bank_proto_rawDesc), len(file_bank_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bank_bank_proto_goTypes,
		DependencyIndexes: file_bank_bank_proto_depIdxs,
	}.Build()
	File_bank_bank_proto = out.File
	file_bank_bank_proto_goTypes = nil
	file_bank_bank_proto_depIdxs = nil
}
