// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: bank/card.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardType      string                 `protobuf:"bytes,2,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardBrand     string                 `protobuf:"bytes,3,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_bank_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_bank_card_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCardRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateCardRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CreateCardRequest) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

func (x *CreateCardRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CardResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CardId         string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	CardNumber     string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType       string                 `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardBrand      string                 `protobuf:"bytes,4,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	CreationDate   string                 `protobuf:"bytes,5,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	ExpirationDate string                 `protobuf:"bytes,6,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	AccountNumber  string                 `protobuf:"bytes,7,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Cvv            string                 `protobuf:"bytes,8,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Limit          int64                  `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`
	Status         string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	mi := &file_bank_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_bank_card_proto_rawDescGZIP(), []int{1}
}

func (x *CardResponse) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CardResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CardResponse) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

func (x *CardResponse) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *CardResponse) GetExpirationDate() string {
	if x != nil {
		return x.ExpirationDate
	}
	return ""
}

func (x *CardResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CardResponse) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *CardResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CardResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RequestCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CardType      string                 `protobuf:"bytes,2,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardBrand     string                 `protobuf:"bytes,3,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCardRequest) Reset() {
	*x = RequestCardRequest{}
	mi := &file_bank_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCardRequest) ProtoMessage() {}

func (x *RequestCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCardRequest.ProtoReflect.Descriptor instead.
func (*RequestCardRequest) Descriptor() ([]byte, []int) {
	return file_bank_card_proto_rawDescGZIP(), []int{2}
}

func (x *RequestCardRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *RequestCardRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *RequestCardRequest) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

type RequestCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCardResponse) Reset() {
	*x = RequestCardResponse{}
	mi := &file_bank_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCardResponse) ProtoMessage() {}

func (x *RequestCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCardResponse.ProtoReflect.Descriptor instead.
func (*RequestCardResponse) Descriptor() ([]byte, []int) {
	return file_bank_card_proto_rawDescGZIP(), []int{3}
}

func (x *RequestCardResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ConfirmCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmCardRequest) Reset() {
	*x = ConfirmCardRequest{}
	mi := &file_bank_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmCardRequest) ProtoMessage() {}

func (x *ConfirmCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmCardRequest.ProtoReflect.Descriptor instead.
func (*ConfirmCardRequest) Descriptor() ([]byte, []int) {
	return file_bank_card_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmCardRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ConfirmCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmCardResponse) Reset() {
	*x = ConfirmCardResponse{}
	mi := &file_bank_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmCardResponse) ProtoMessage() {}

func (x *ConfirmCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmCardResponse.ProtoReflect.Descriptor instead.
func (*ConfirmCardResponse) Descriptor() ([]byte, []int) {
	return file_bank_card_proto_rawDescGZIP(), []int{5}
}

type GetCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsRequest) Reset() {
	*x = GetCardsRequest{}
	mi := &file_bank_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsRequest) ProtoMessage() {}

func (x *GetCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsRequest.ProtoReflect.Descriptor instead.
func (*GetCardsRequest) Descriptor() ([]byte, []int) {
	return file_bank_card_proto_rawDescGZIP(), []int{6}
}

type GetCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*CardResponse        `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsResponse) Reset() {
	*x = GetCardsResponse{}
	mi := &file_bank_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsResponse) ProtoMessage() {}

func (x *GetCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsResponse.ProtoReflect.Descriptor instead.
func (*GetCardsResponse) Descriptor() ([]byte, []int) {
	return file_bank_card_proto_rawDescGZIP(), []int{7}
}

func (x *GetCardsResponse) GetCards() []*CardResponse {
	if x != nil {
		return x.Cards
	}
	return nil
}

type BlockCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCardRequest) Reset() {
	*x = BlockCardRequest{}
	mi := &file_bank_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCardRequest) ProtoMessage() {}

func (x *BlockCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCardRequest.ProtoReflect.Descriptor instead.
func (*BlockCardRequest) Descriptor() ([]byte, []int) {
	return file_bank_card_proto_rawDescGZIP(), []int{8}
}

func (x *BlockCardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

type BlockCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCardResponse) Reset() {
	*x = BlockCardResponse{}
	mi := &file_bank_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCardResponse) ProtoMessage() {}

func (x *BlockCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCardResponse.ProtoReflect.Descriptor instead.
func (*BlockCardResponse) Descriptor() ([]byte, []int) {
	return file_bank_card_proto_rawDescGZIP(), []int{9}
}

func (x *BlockCardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_bank_card_proto protoreflect.FileDescriptor

const file_bank_card_proto_rawDesc = "" +
	"\n" +
	"\x0fbank/card.proto\x12\x04bank\"\x8c\x01\n" +
	"\x11CreateCardRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x1b\n" +
	"\tcard_type\x18\x02 \x01(\tR\bcardType\x12\x1d\n" +
	"\n" +
	"card_brand\x18\x03 \x01(\tR\tcardBrand\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\xb9\x02\n" +
	"\fCardResponse\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x03 \x01(\tR\bcardType\x12\x1d\n" +
	"\n" +
	"card_brand\x18\x04 \x01(\tR\tcardBrand\x12#\n" +
	"\rcreation_date\x18\x05 \x01(\tR\fcreationDate\x12'\n" +
	"\x0fexpiration_date\x18\x06 \x01(\tR\x0eexpirationDate\x12%\n" +
	"\x0eaccount_number\x18\a \x01(\tR\raccountNumber\x12\x10\n" +
	"\x03cvv\x18\b \x01(\tR\x03cvv\x12\x14\n" +
	"\x05limit\x18\t \x01(\x03R\x05limit\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"w\n" +
	"\x12RequestCardRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x1b\n" +
	"\tcard_type\x18\x02 \x01(\tR\bcardType\x12\x1d\n" +
	"\n" +
	"card_brand\x18\x03 \x01(\tR\tcardBrand\"1\n" +
	"\x13RequestCardResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"*\n" +
	"\x12ConfirmCardRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x15\n" +
	"\x13ConfirmCardResponse\"\x11\n" +
	"\x0fGetCardsRequest\"<\n" +
	"\x10GetCardsResponse\x12(\n" +
	"\x05cards\x18\x01 \x03(\v2\x12.bank.CardResponseR\x05cards\"3\n" +
	"\x10BlockCardRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\"-\n" +
	"\x11BlockCardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB7Z5github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/bankb\x06proto3"

var (
	file_bank_card_proto_rawDescOnce sync.Once
	file_bank_card_proto_rawDescData []byte
)

func file_bank_card_proto_rawDescGZIP() []byte {
	file_bank_card_proto_rawDescOnce.Do(func() {
		file_bank_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bank_card_proto_rawDesc), len(file_bank_card_proto_rawDesc)))
	})
	return file_bank_card_proto_rawDescData
}

var file_bank_card_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bank_card_proto_goTypes = []any{
	(*CreateCardRequest)(nil),   // 0: bank.CreateCardRequest
	(*CardResponse)(nil),        // 1: bank.CardResponse
	(*RequestCardRequest)(nil),  // 2: bank.RequestCardRequest
	(*RequestCardResponse)(nil), // 3: bank.RequestCardResponse
	(*ConfirmCardRequest)(nil),  // 4: bank.ConfirmCardRequest
	(*ConfirmCardResponse)(nil), // 5: bank.ConfirmCardResponse
	(*GetCardsRequest)(nil),     // 6: bank.GetCardsRequest
	(*GetCardsResponse)(nil),    // 7: bank.GetCardsResponse
	(*BlockCardRequest)(nil),    // 8: bank.BlockCardRequest
	(*BlockCardResponse)(nil),   // 9: bank.BlockCardResponse
}
var file_bank_card_proto_depIdxs = []int32{
	1, // 0: bank.GetCardsResponse.cards:type_name -> bank.CardResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bank_card_proto_init() }
func file_bank_card_proto_init() {
	if File_bank_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_card_proto_rawDesc), len(file_bank_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bank_card_proto_goTypes,
		DependencyIndexes: file_bank_card_proto_depIdxs,
		MessageInfos:      file_bank_card_proto_msgTypes,
	}.Build()
	File_bank_card_proto = out.File
	file_bank_card_proto_goTypes = nil
	file_bank_card_proto_depIdxs = nil
}
