// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: bank/loan.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Loan struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LoanNumber            string                 `protobuf:"bytes,1,opt,name=loan_number,json=loanNumber,proto3" json:"loan_number,omitempty"`
	LoanType              string                 `protobuf:"bytes,2,opt,name=loan_type,json=loanType,proto3" json:"loan_type,omitempty"`
	AccountNumber         string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	LoanAmount            int64                  `protobuf:"varint,4,opt,name=loan_amount,json=loanAmount,proto3" json:"loan_amount,omitempty"`
	RepaymentPeriod       int64                  `protobuf:"varint,5,opt,name=repayment_period,json=repaymentPeriod,proto3" json:"repayment_period,omitempty"`
	NominalRate           float64                `protobuf:"fixed64,6,opt,name=nominal_rate,json=nominalRate,proto3" json:"nominal_rate,omitempty"`
	EffectiveRate         float64                `protobuf:"fixed64,7,opt,name=effective_rate,json=effectiveRate,proto3" json:"effective_rate,omitempty"`
	AgreementDate         string                 `protobuf:"bytes,8,opt,name=agreement_date,json=agreementDate,proto3" json:"agreement_date,omitempty"`
	MaturityDate          string                 `protobuf:"bytes,9,opt,name=maturity_date,json=maturityDate,proto3" json:"maturity_date,omitempty"`
	NextInstallmentAmount int64                  `protobuf:"varint,10,opt,name=next_installment_amount,json=nextInstallmentAmount,proto3" json:"next_installment_amount,omitempty"`
	NextInstallmentDate   string                 `protobuf:"bytes,11,opt,name=next_installment_date,json=nextInstallmentDate,proto3" json:"next_installment_date,omitempty"`
	RemainingDebt         int64                  `protobuf:"varint,12,opt,name=remaining_debt,json=remainingDebt,proto3" json:"remaining_debt,omitempty"`
	Currency              string                 `protobuf:"bytes,13,opt,name=currency,proto3" json:"currency,omitempty"`
	Status                string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Loan) Reset() {
	*x = Loan{}
	mi := &file_bank_loan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loan) ProtoMessage() {}

func (x *Loan) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loan.ProtoReflect.Descriptor instead.
func (*Loan) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{0}
}

func (x *Loan) GetLoanNumber() string {
	if x != nil {
		return x.LoanNumber
	}
	return ""
}

func (x *Loan) GetLoanType() string {
	if x != nil {
		return x.LoanType
	}
	return ""
}

func (x *Loan) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Loan) GetLoanAmount() int64 {
	if x != nil {
		return x.LoanAmount
	}
	return 0
}

func (x *Loan) GetRepaymentPeriod() int64 {
	if x != nil {
		return x.RepaymentPeriod
	}
	return 0
}

func (x *Loan) GetNominalRate() float64 {
	if x != nil {
		return x.NominalRate
	}
	return 0
}

func (x *Loan) GetEffectiveRate() float64 {
	if x != nil {
		return x.EffectiveRate
	}
	return 0
}

func (x *Loan) GetAgreementDate() string {
	if x != nil {
		return x.AgreementDate
	}
	return ""
}

func (x *Loan) GetMaturityDate() string {
	if x != nil {
		return x.MaturityDate
	}
	return ""
}

func (x *Loan) GetNextInstallmentAmount() int64 {
	if x != nil {
		return x.NextInstallmentAmount
	}
	return 0
}

func (x *Loan) GetNextInstallmentDate() string {
	if x != nil {
		return x.NextInstallmentDate
	}
	return ""
}

func (x *Loan) GetRemainingDebt() int64 {
	if x != nil {
		return x.RemainingDebt
	}
	return 0
}

func (x *Loan) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Loan) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LoanRequestView struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LoanType         string                 `protobuf:"bytes,2,opt,name=loan_type,json=loanType,proto3" json:"loan_type,omitempty"`
	Amount           int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Purpose          string                 `protobuf:"bytes,5,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Salary           int64                  `protobuf:"varint,6,opt,name=salary,proto3" json:"salary,omitempty"`
	EmploymentStatus string                 `protobuf:"bytes,7,opt,name=employment_status,json=employmentStatus,proto3" json:"employment_status,omitempty"`
	EmploymentPeriod int64                  `protobuf:"varint,8,opt,name=employment_period,json=employmentPeriod,proto3" json:"employment_period,omitempty"`
	PhoneNumber      string                 `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	RepaymentPeriod  int64                  `protobuf:"varint,10,opt,name=repayment_period,json=repaymentPeriod,proto3" json:"repayment_period,omitempty"`
	AccountNumber    string                 `protobuf:"bytes,11,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Status           string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	InterestRateType string                 `protobuf:"bytes,13,opt,name=interest_rate_type,json=interestRateType,proto3" json:"interest_rate_type,omitempty"`
	SubmissionDate   string                 `protobuf:"bytes,14,opt,name=submission_date,json=submissionDate,proto3" json:"submission_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoanRequestView) Reset() {
	*x = LoanRequestView{}
	mi := &file_bank_loan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanRequestView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanRequestView) ProtoMessage() {}

func (x *LoanRequestView) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanRequestView.ProtoReflect.Descriptor instead.
func (*LoanRequestView) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{1}
}

func (x *LoanRequestView) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoanRequestView) GetLoanType() string {
	if x != nil {
		return x.LoanType
	}
	return ""
}

func (x *LoanRequestView) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LoanRequestView) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *LoanRequestView) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *LoanRequestView) GetSalary() int64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *LoanRequestView) GetEmploymentStatus() string {
	if x != nil {
		return x.EmploymentStatus
	}
	return ""
}

func (x *LoanRequestView) GetEmploymentPeriod() int64 {
	if x != nil {
		return x.EmploymentPeriod
	}
	return 0
}

func (x *LoanRequestView) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *LoanRequestView) GetRepaymentPeriod() int64 {
	if x != nil {
		return x.RepaymentPeriod
	}
	return 0
}

func (x *LoanRequestView) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *LoanRequestView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoanRequestView) GetInterestRateType() string {
	if x != nil {
		return x.InterestRateType
	}
	return ""
}

func (x *LoanRequestView) GetSubmissionDate() string {
	if x != nil {
		return x.SubmissionDate
	}
	return ""
}

type GetLoansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientEmail   string                 `protobuf:"bytes,1,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	LoanType      string                 `protobuf:"bytes,2,opt,name=loan_type,json=loanType,proto3" json:"loan_type,omitempty"`
	AccountNumber string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoansRequest) Reset() {
	*x = GetLoansRequest{}
	mi := &file_bank_loan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoansRequest) ProtoMessage() {}

func (x *GetLoansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoansRequest.ProtoReflect.Descriptor instead.
func (*GetLoansRequest) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{2}
}

func (x *GetLoansRequest) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *GetLoansRequest) GetLoanType() string {
	if x != nil {
		return x.LoanType
	}
	return ""
}

func (x *GetLoansRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *GetLoansRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetLoansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loans         []*Loan                `protobuf:"bytes,1,rep,name=loans,proto3" json:"loans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoansResponse) Reset() {
	*x = GetLoansResponse{}
	mi := &file_bank_loan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoansResponse) ProtoMessage() {}

func (x *GetLoansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoansResponse.ProtoReflect.Descriptor instead.
func (*GetLoansResponse) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{3}
}

func (x *GetLoansResponse) GetLoans() []*Loan {
	if x != nil {
		return x.Loans
	}
	return nil
}

type GetLoanByNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientEmail   string                 `protobuf:"bytes,1,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	LoanNumber    string                 `protobuf:"bytes,2,opt,name=loan_number,json=loanNumber,proto3" json:"loan_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanByNumberRequest) Reset() {
	*x = GetLoanByNumberRequest{}
	mi := &file_bank_loan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanByNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanByNumberRequest) ProtoMessage() {}

func (x *GetLoanByNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanByNumberRequest.ProtoReflect.Descriptor instead.
func (*GetLoanByNumberRequest) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{4}
}

func (x *GetLoanByNumberRequest) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *GetLoanByNumberRequest) GetLoanNumber() string {
	if x != nil {
		return x.LoanNumber
	}
	return ""
}

type CreateLoanRequestRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientEmail      string                 `protobuf:"bytes,1,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	AccountNumber    string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	LoanType         string                 `protobuf:"bytes,3,opt,name=loan_type,json=loanType,proto3" json:"loan_type,omitempty"`
	Amount           int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	RepaymentPeriod  int64                  `protobuf:"varint,5,opt,name=repayment_period,json=repaymentPeriod,proto3" json:"repayment_period,omitempty"`
	Currency         string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Purpose          string                 `protobuf:"bytes,7,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Salary           int64                  `protobuf:"varint,8,opt,name=salary,proto3" json:"salary,omitempty"`
	EmploymentStatus string                 `protobuf:"bytes,9,opt,name=employment_status,json=employmentStatus,proto3" json:"employment_status,omitempty"`
	EmploymentPeriod int64                  `protobuf:"varint,10,opt,name=employment_period,json=employmentPeriod,proto3" json:"employment_period,omitempty"`
	PhoneNumber      string                 `protobuf:"bytes,11,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	InterestRateType string                 `protobuf:"bytes,12,opt,name=interest_rate_type,json=interestRateType,proto3" json:"interest_rate_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateLoanRequestRequest) Reset() {
	*x = CreateLoanRequestRequest{}
	mi := &file_bank_loan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanRequestRequest) ProtoMessage() {}

func (x *CreateLoanRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateLoanRequestRequest) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{5}
}

func (x *CreateLoanRequestRequest) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *CreateLoanRequestRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateLoanRequestRequest) GetLoanType() string {
	if x != nil {
		return x.LoanType
	}
	return ""
}

func (x *CreateLoanRequestRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateLoanRequestRequest) GetRepaymentPeriod() int64 {
	if x != nil {
		return x.RepaymentPeriod
	}
	return 0
}

func (x *CreateLoanRequestRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateLoanRequestRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *CreateLoanRequestRequest) GetSalary() int64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *CreateLoanRequestRequest) GetEmploymentStatus() string {
	if x != nil {
		return x.EmploymentStatus
	}
	return ""
}

func (x *CreateLoanRequestRequest) GetEmploymentPeriod() int64 {
	if x != nil {
		return x.EmploymentPeriod
	}
	return 0
}

func (x *CreateLoanRequestRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateLoanRequestRequest) GetInterestRateType() string {
	if x != nil {
		return x.InterestRateType
	}
	return ""
}

type CreateLoanRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanRequestResponse) Reset() {
	*x = CreateLoanRequestResponse{}
	mi := &file_bank_loan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanRequestResponse) ProtoMessage() {}

func (x *CreateLoanRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateLoanRequestResponse) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{6}
}

type GetLoanRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanType      string                 `protobuf:"bytes,1,opt,name=loan_type,json=loanType,proto3" json:"loan_type,omitempty"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanRequestsRequest) Reset() {
	*x = GetLoanRequestsRequest{}
	mi := &file_bank_loan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanRequestsRequest) ProtoMessage() {}

func (x *GetLoanRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetLoanRequestsRequest) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{7}
}

func (x *GetLoanRequestsRequest) GetLoanType() string {
	if x != nil {
		return x.LoanType
	}
	return ""
}

func (x *GetLoanRequestsRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type GetLoanRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanRequests  []*LoanRequestView     `protobuf:"bytes,1,rep,name=loan_requests,json=loanRequests,proto3" json:"loan_requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanRequestsResponse) Reset() {
	*x = GetLoanRequestsResponse{}
	mi := &file_bank_loan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanRequestsResponse) ProtoMessage() {}

func (x *GetLoanRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetLoanRequestsResponse) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{8}
}

func (x *GetLoanRequestsResponse) GetLoanRequests() []*LoanRequestView {
	if x != nil {
		return x.LoanRequests
	}
	return nil
}

type ApproveLoanRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveLoanRequestRequest) Reset() {
	*x = ApproveLoanRequestRequest{}
	mi := &file_bank_loan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveLoanRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveLoanRequestRequest) ProtoMessage() {}

func (x *ApproveLoanRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveLoanRequestRequest.ProtoReflect.Descriptor instead.
func (*ApproveLoanRequestRequest) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{9}
}

func (x *ApproveLoanRequestRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ApproveLoanRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveLoanRequestResponse) Reset() {
	*x = ApproveLoanRequestResponse{}
	mi := &file_bank_loan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveLoanRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveLoanRequestResponse) ProtoMessage() {}

func (x *ApproveLoanRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveLoanRequestResponse.ProtoReflect.Descriptor instead.
func (*ApproveLoanRequestResponse) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{10}
}

type RejectLoanRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectLoanRequestRequest) Reset() {
	*x = RejectLoanRequestRequest{}
	mi := &file_bank_loan_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectLoanRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectLoanRequestRequest) ProtoMessage() {}

func (x *RejectLoanRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectLoanRequestRequest.ProtoReflect.Descriptor instead.
func (*RejectLoanRequestRequest) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{11}
}

func (x *RejectLoanRequestRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RejectLoanRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectLoanRequestResponse) Reset() {
	*x = RejectLoanRequestResponse{}
	mi := &file_bank_loan_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectLoanRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectLoanRequestResponse) ProtoMessage() {}

func (x *RejectLoanRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectLoanRequestResponse.ProtoReflect.Descriptor instead.
func (*RejectLoanRequestResponse) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{12}
}

type GetAllLoansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanType      string                 `protobuf:"bytes,1,opt,name=loan_type,json=loanType,proto3" json:"loan_type,omitempty"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllLoansRequest) Reset() {
	*x = GetAllLoansRequest{}
	mi := &file_bank_loan_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllLoansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLoansRequest) ProtoMessage() {}

func (x *GetAllLoansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_loan_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLoansRequest.ProtoReflect.Descriptor instead.
func (*GetAllLoansRequest) Descriptor() ([]byte, []int) {
	return file_bank_loan_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllLoansRequest) GetLoanType() string {
	if x != nil {
		return x.LoanType
	}
	return ""
}

func (x *GetAllLoansRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *GetAllLoansRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_bank_loan_proto protoreflect.FileDescriptor

const file_bank_loan_proto_rawDesc = "" +
	"\n" +
	"\x0fbank/loan.proto\x12\x04bank\"\x94\x04\n" +
	"\x04Loan\x12\x1f\n" +
	"\vloan_number\x18\x01 \x01(\tR\n" +
	"loanNumber\x12\x1b\n" +
	"\tloan_type\x18\x02 \x01(\tR\bloanType\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12\x1f\n" +
	"\vloan_amount\x18\x04 \x01(\x03R\n" +
	"loanAmount\x12)\n" +
	"\x10repayment_period\x18\x05 \x01(\x03R\x0frepaymentPeriod\x12!\n" +
	"\fnominal_rate\x18\x06 \x01(\x01R\vnominalRate\x12%\n" +
	"\x0eeffective_rate\x18\a \x01(\x01R\reffectiveRate\x12%\n" +
	"\x0eagreement_date\x18\b \x01(\tR\ragreementDate\x12#\n" +
	"\rmaturity_date\x18\t \x01(\tR\fmaturityDate\x126\n" +
	"\x17next_installment_amount\x18\n" +
	" \x01(\x03R\x15nextInstallmentAmount\x122\n" +
	"\x15next_installment_date\x18\v \x01(\tR\x13nextInstallmentDate\x12%\n" +
	"\x0eremaining_debt\x18\f \x01(\x03R\rremainingDebt\x12\x1a\n" +
	"\bcurrency\x18\r \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\"\xe2\x03\n" +
	"\x0fLoanRequestView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tloan_type\x18\x02 \x01(\tR\bloanType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x18\n" +
	"\apurpose\x18\x05 \x01(\tR\apurpose\x12\x16\n" +
	"\x06salary\x18\x06 \x01(\x03R\x06salary\x12+\n" +
	"\x11employment_status\x18\a \x01(\tR\x10employmentStatus\x12+\n" +
	"\x11employment_period\x18\b \x01(\x03R\x10employmentPeriod\x12!\n" +
	"\fphone_number\x18\t \x01(\tR\vphoneNumber\x12)\n" +
	"\x10repayment_period\x18\n" +
	" \x01(\x03R\x0frepaymentPeriod\x12%\n" +
	"\x0eaccount_number\x18\v \x01(\tR\raccountNumber\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12,\n" +
	"\x12interest_rate_type\x18\r \x01(\tR\x10interestRateType\x12'\n" +
	"\x0fsubmission_date\x18\x0e \x01(\tR\x0esubmissionDate\"\x90\x01\n" +
	"\x0fGetLoansRequest\x12!\n" +
	"\fclient_email\x18\x01 \x01(\tR\vclientEmail\x12\x1b\n" +
	"\tloan_type\x18\x02 \x01(\tR\bloanType\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"4\n" +
	"\x10GetLoansResponse\x12 \n" +
	"\x05loans\x18\x01 \x03(\v2\n" +
	".bank.LoanR\x05loans\"\\\n" +
	"\x16GetLoanByNumberRequest\x12!\n" +
	"\fclient_email\x18\x01 \x01(\tR\vclientEmail\x12\x1f\n" +
	"\vloan_number\x18\x02 \x01(\tR\n" +
	"loanNumber\"\xbd\x03\n" +
	"\x18CreateLoanRequestRequest\x12!\n" +
	"\fclient_email\x18\x01 \x01(\tR\vclientEmail\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12\x1b\n" +
	"\tloan_type\x18\x03 \x01(\tR\bloanType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12)\n" +
	"\x10repayment_period\x18\x05 \x01(\x03R\x0frepaymentPeriod\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x18\n" +
	"\apurpose\x18\a \x01(\tR\apurpose\x12\x16\n" +
	"\x06salary\x18\b \x01(\x03R\x06salary\x12+\n" +
	"\x11employment_status\x18\t \x01(\tR\x10employmentStatus\x12+\n" +
	"\x11employment_period\x18\n" +
	" \x01(\x03R\x10employmentPeriod\x12!\n" +
	"\fphone_number\x18\v \x01(\tR\vphoneNumber\x12,\n" +
	"\x12interest_rate_type\x18\f \x01(\tR\x10interestRateType\"\x1b\n" +
	"\x19CreateLoanRequestResponse\"\\\n" +
	"\x16GetLoanRequestsRequest\x12\x1b\n" +
	"\tloan_type\x18\x01 \x01(\tR\bloanType\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\"U\n" +
	"\x17GetLoanRequestsResponse\x12:\n" +
	"\rloan_requests\x18\x01 \x03(\v2\x15.bank.LoanRequestViewR\floanRequests\"+\n" +
	"\x19ApproveLoanRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1c\n" +
	"\x1aApproveLoanRequestResponse\"*\n" +
	"\x18RejectLoanRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1b\n" +
	"\x19RejectLoanRequestResponse\"p\n" +
	"\x12GetAllLoansRequest\x12\x1b\n" +
	"\tloan_type\x18\x01 \x01(\tR\bloanType\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06statusB7Z5github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/bankb\x06proto3"

var (
	file_bank_loan_proto_rawDescOnce sync.Once
	file_bank_loan_proto_rawDescData []byte
)

func file_bank_loan_proto_rawDescGZIP() []byte {
	file_bank_loan_proto_rawDescOnce.Do(func() {
		file_bank_loan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bank_loan_proto_rawDesc), len(file_bank_loan_proto_rawDesc)))
	})
	return file_bank_loan_proto_rawDescData
}

var file_bank_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_bank_loan_proto_goTypes = []any{
	(*Loan)(nil),                       // 0: bank.Loan
	(*LoanRequestView)(nil),            // 1: bank.LoanRequestView
	(*GetLoansRequest)(nil),            // 2: bank.GetLoansRequest
	(*GetLoansResponse)(nil),           // 3: bank.GetLoansResponse
	(*GetLoanByNumberRequest)(nil),     // 4: bank.GetLoanByNumberRequest
	(*CreateLoanRequestRequest)(nil),   // 5: bank.CreateLoanRequestRequest
	(*CreateLoanRequestResponse)(nil),  // 6: bank.CreateLoanRequestResponse
	(*GetLoanRequestsRequest)(nil),     // 7: bank.GetLoanRequestsRequest
	(*GetLoanRequestsResponse)(nil),    // 8: bank.GetLoanRequestsResponse
	(*ApproveLoanRequestRequest)(nil),  // 9: bank.ApproveLoanRequestRequest
	(*ApproveLoanRequestResponse)(nil), // 10: bank.ApproveLoanRequestResponse
	(*RejectLoanRequestRequest)(nil),   // 11: bank.RejectLoanRequestRequest
	(*RejectLoanRequestResponse)(nil),  // 12: bank.RejectLoanRequestResponse
	(*GetAllLoansRequest)(nil),         // 13: bank.GetAllLoansRequest
}
var file_bank_loan_proto_depIdxs = []int32{
	0, // 0: bank.GetLoansResponse.loans:type_name -> bank.Loan
	1, // 1: bank.GetLoanRequestsResponse.loan_requests:type_name -> bank.LoanRequestView
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bank_loan_proto_init() }
func file_bank_loan_proto_init() {
	if File_bank_loan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_loan_proto_rawDesc), len(file_bank_loan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bank_loan_proto_goTypes,
		DependencyIndexes: file_bank_loan_proto_depIdxs,
		MessageInfos:      file_bank_loan_proto_msgTypes,
	}.Build()
	File_bank_loan_proto = out.File
	file_bank_loan_proto_goTypes = nil
	file_bank_loan_proto_depIdxs = nil
}
