// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: bank/recipient.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentRecipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccountNumber string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRecipient) Reset() {
	*x = PaymentRecipient{}
	mi := &file_bank_recipient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRecipient) ProtoMessage() {}

func (x *PaymentRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_bank_recipient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRecipient.ProtoReflect.Descriptor instead.
func (*PaymentRecipient) Descriptor() ([]byte, []int) {
	return file_bank_recipient_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRecipient) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentRecipient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentRecipient) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type GetPaymentRecipientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRecipientsRequest) Reset() {
	*x = GetPaymentRecipientsRequest{}
	mi := &file_bank_recipient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRecipientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRecipientsRequest) ProtoMessage() {}

func (x *GetPaymentRecipientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_recipient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRecipientsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRecipientsRequest) Descriptor() ([]byte, []int) {
	return file_bank_recipient_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentRecipientsRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GetPaymentRecipientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    []*PaymentRecipient    `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRecipientsResponse) Reset() {
	*x = GetPaymentRecipientsResponse{}
	mi := &file_bank_recipient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRecipientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRecipientsResponse) ProtoMessage() {}

func (x *GetPaymentRecipientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_recipient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRecipientsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentRecipientsResponse) Descriptor() ([]byte, []int) {
	return file_bank_recipient_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentRecipientsResponse) GetRecipients() []*PaymentRecipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

type CreatePaymentRecipientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccountNumber string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRecipientRequest) Reset() {
	*x = CreatePaymentRecipientRequest{}
	mi := &file_bank_recipient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRecipientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRecipientRequest) ProtoMessage() {}

func (x *CreatePaymentRecipientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_recipient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRecipientRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRecipientRequest) Descriptor() ([]byte, []int) {
	return file_bank_recipient_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePaymentRecipientRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreatePaymentRecipientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePaymentRecipientRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type CreatePaymentRecipientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     *PaymentRecipient      `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRecipientResponse) Reset() {
	*x = CreatePaymentRecipientResponse{}
	mi := &file_bank_recipient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRecipientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRecipientResponse) ProtoMessage() {}

func (x *CreatePaymentRecipientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_recipient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRecipientResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentRecipientResponse) Descriptor() ([]byte, []int) {
	return file_bank_recipient_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePaymentRecipientResponse) GetRecipient() *PaymentRecipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

type UpdatePaymentRecipientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AccountNumber string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRecipientRequest) Reset() {
	*x = UpdatePaymentRecipientRequest{}
	mi := &file_bank_recipient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRecipientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRecipientRequest) ProtoMessage() {}

func (x *UpdatePaymentRecipientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_recipient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRecipientRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRecipientRequest) Descriptor() ([]byte, []int) {
	return file_bank_recipient_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePaymentRecipientRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePaymentRecipientRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *UpdatePaymentRecipientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePaymentRecipientRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type UpdatePaymentRecipientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     *PaymentRecipient      `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRecipientResponse) Reset() {
	*x = UpdatePaymentRecipientResponse{}
	mi := &file_bank_recipient_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRecipientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRecipientResponse) ProtoMessage() {}

func (x *UpdatePaymentRecipientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_recipient_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRecipientResponse.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRecipientResponse) Descriptor() ([]byte, []int) {
	return file_bank_recipient_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePaymentRecipientResponse) GetRecipient() *PaymentRecipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

type DeletePaymentRecipientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentRecipientRequest) Reset() {
	*x = DeletePaymentRecipientRequest{}
	mi := &file_bank_recipient_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentRecipientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentRecipientRequest) ProtoMessage() {}

func (x *DeletePaymentRecipientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_recipient_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentRecipientRequest.ProtoReflect.Descriptor instead.
func (*DeletePaymentRecipientRequest) Descriptor() ([]byte, []int) {
	return file_bank_recipient_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePaymentRecipientRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeletePaymentRecipientRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type DeletePaymentRecipientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentRecipientResponse) Reset() {
	*x = DeletePaymentRecipientResponse{}
	mi := &file_bank_recipient_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentRecipientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentRecipientResponse) ProtoMessage() {}

func (x *DeletePaymentRecipientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_recipient_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentRecipientResponse.ProtoReflect.Descriptor instead.
func (*DeletePaymentRecipientResponse) Descriptor() ([]byte, []int) {
	return file_bank_recipient_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePaymentRecipientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_bank_recipient_proto protoreflect.FileDescriptor

const file_bank_recipient_proto_rawDesc = "" +
	"\n" +
	"\x14bank/recipient.proto\x12\x04bank\"]\n" +
	"\x10PaymentRecipient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\":\n" +
	"\x1bGetPaymentRecipientsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\"V\n" +
	"\x1cGetPaymentRecipientsResponse\x126\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2\x16.bank.PaymentRecipientR\n" +
	"recipients\"w\n" +
	"\x1dCreatePaymentRecipientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\"V\n" +
	"\x1eCreatePaymentRecipientResponse\x124\n" +
	"\trecipient\x18\x01 \x01(\v2\x16.bank.PaymentRecipientR\trecipient\"\x87\x01\n" +
	"\x1dUpdatePaymentRecipientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\"V\n" +
	"\x1eUpdatePaymentRecipientResponse\x124\n" +
	"\trecipient\x18\x01 \x01(\v2\x16.bank.PaymentRecipientR\trecipient\"L\n" +
	"\x1dDeletePaymentRecipientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\":\n" +
	"\x1eDeletePaymentRecipientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB7Z5github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/bankb\x06proto3"

var (
	file_bank_recipient_proto_rawDescOnce sync.Once
	file_bank_recipient_proto_rawDescData []byte
)

func file_bank_recipient_proto_rawDescGZIP() []byte {
	file_bank_recipient_proto_rawDescOnce.Do(func() {
		file_bank_recipient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bank_recipient_proto_rawDesc), len(file_bank_recipient_proto_rawDesc)))
	})
	return file_bank_recipient_proto_rawDescData
}

var file_bank_recipient_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bank_recipient_proto_goTypes = []any{
	(*PaymentRecipient)(nil),               // 0: bank.PaymentRecipient
	(*GetPaymentRecipientsRequest)(nil),    // 1: bank.GetPaymentRecipientsRequest
	(*GetPaymentRecipientsResponse)(nil),   // 2: bank.GetPaymentRecipientsResponse
	(*CreatePaymentRecipientRequest)(nil),  // 3: bank.CreatePaymentRecipientRequest
	(*CreatePaymentRecipientResponse)(nil), // 4: bank.CreatePaymentRecipientResponse
	(*UpdatePaymentRecipientRequest)(nil),  // 5: bank.UpdatePaymentRecipientRequest
	(*UpdatePaymentRecipientResponse)(nil), // 6: bank.UpdatePaymentRecipientResponse
	(*DeletePaymentRecipientRequest)(nil),  // 7: bank.DeletePaymentRecipientRequest
	(*DeletePaymentRecipientResponse)(nil), // 8: bank.DeletePaymentRecipientResponse
}
var file_bank_recipient_proto_depIdxs = []int32{
	0, // 0: bank.GetPaymentRecipientsResponse.recipients:type_name -> bank.PaymentRecipient
	0, // 1: bank.CreatePaymentRecipientResponse.recipient:type_name -> bank.PaymentRecipient
	0, // 2: bank.UpdatePaymentRecipientResponse.recipient:type_name -> bank.PaymentRecipient
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bank_recipient_proto_init() }
func file_bank_recipient_proto_init() {
	if File_bank_recipient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_recipient_proto_rawDesc), len(file_bank_recipient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bank_recipient_proto_goTypes,
		DependencyIndexes: file_bank_recipient_proto_depIdxs,
		MessageInfos:      file_bank_recipient_proto_msgTypes,
	}.Build()
	File_bank_recipient_proto = out.File
	file_bank_recipient_proto_goTypes = nil
	file_bank_recipient_proto_depIdxs = nil
}
