// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: bank/recipient.proto

package bank

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentRecipientService_GetPaymentRecipients_FullMethodName   = "/bank.PaymentRecipientService/GetPaymentRecipients"
	PaymentRecipientService_CreatePaymentRecipient_FullMethodName = "/bank.PaymentRecipientService/CreatePaymentRecipient"
	PaymentRecipientService_UpdatePaymentRecipient_FullMethodName = "/bank.PaymentRecipientService/UpdatePaymentRecipient"
	PaymentRecipientService_DeletePaymentRecipient_FullMethodName = "/bank.PaymentRecipientService/DeletePaymentRecipient"
)

// PaymentRecipientServiceClient is the client API for PaymentRecipientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentRecipientServiceClient interface {
	GetPaymentRecipients(ctx context.Context, in *GetPaymentRecipientsRequest, opts ...grpc.CallOption) (*GetPaymentRecipientsResponse, error)
	CreatePaymentRecipient(ctx context.Context, in *CreatePaymentRecipientRequest, opts ...grpc.CallOption) (*CreatePaymentRecipientResponse, error)
	UpdatePaymentRecipient(ctx context.Context, in *UpdatePaymentRecipientRequest, opts ...grpc.CallOption) (*UpdatePaymentRecipientResponse, error)
	DeletePaymentRecipient(ctx context.Context, in *DeletePaymentRecipientRequest, opts ...grpc.CallOption) (*DeletePaymentRecipientResponse, error)
}

type paymentRecipientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentRecipientServiceClient(cc grpc.ClientConnInterface) PaymentRecipientServiceClient {
	return &paymentRecipientServiceClient{cc}
}

func (c *paymentRecipientServiceClient) GetPaymentRecipients(ctx context.Context, in *GetPaymentRecipientsRequest, opts ...grpc.CallOption) (*GetPaymentRecipientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentRecipientsResponse)
	err := c.cc.Invoke(ctx, PaymentRecipientService_GetPaymentRecipients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentRecipientServiceClient) CreatePaymentRecipient(ctx context.Context, in *CreatePaymentRecipientRequest, opts ...grpc.CallOption) (*CreatePaymentRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentRecipientResponse)
	err := c.cc.Invoke(ctx, PaymentRecipientService_CreatePaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentRecipientServiceClient) UpdatePaymentRecipient(ctx context.Context, in *UpdatePaymentRecipientRequest, opts ...grpc.CallOption) (*UpdatePaymentRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePaymentRecipientResponse)
	err := c.cc.Invoke(ctx, PaymentRecipientService_UpdatePaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentRecipientServiceClient) DeletePaymentRecipient(ctx context.Context, in *DeletePaymentRecipientRequest, opts ...grpc.CallOption) (*DeletePaymentRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePaymentRecipientResponse)
	err := c.cc.Invoke(ctx, PaymentRecipientService_DeletePaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentRecipientServiceServer is the server API for PaymentRecipientService service.
// All implementations must embed UnimplementedPaymentRecipientServiceServer
// for forward compatibility.
type PaymentRecipientServiceServer interface {
	GetPaymentRecipients(context.Context, *GetPaymentRecipientsRequest) (*GetPaymentRecipientsResponse, error)
	CreatePaymentRecipient(context.Context, *CreatePaymentRecipientRequest) (*CreatePaymentRecipientResponse, error)
	UpdatePaymentRecipient(context.Context, *UpdatePaymentRecipientRequest) (*UpdatePaymentRecipientResponse, error)
	DeletePaymentRecipient(context.Context, *DeletePaymentRecipientRequest) (*DeletePaymentRecipientResponse, error)
	mustEmbedUnimplementedPaymentRecipientServiceServer()
}

// UnimplementedPaymentRecipientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentRecipientServiceServer struct{}

func (UnimplementedPaymentRecipientServiceServer) GetPaymentRecipients(context.Context, *GetPaymentRecipientsRequest) (*GetPaymentRecipientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentRecipients not implemented")
}
func (UnimplementedPaymentRecipientServiceServer) CreatePaymentRecipient(context.Context, *CreatePaymentRecipientRequest) (*CreatePaymentRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePaymentRecipient not implemented")
}
func (UnimplementedPaymentRecipientServiceServer) UpdatePaymentRecipient(context.Context, *UpdatePaymentRecipientRequest) (*UpdatePaymentRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePaymentRecipient not implemented")
}
func (UnimplementedPaymentRecipientServiceServer) DeletePaymentRecipient(context.Context, *DeletePaymentRecipientRequest) (*DeletePaymentRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePaymentRecipient not implemented")
}
func (UnimplementedPaymentRecipientServiceServer) mustEmbedUnimplementedPaymentRecipientServiceServer() {
}
func (UnimplementedPaymentRecipientServiceServer) testEmbeddedByValue() {}

// UnsafePaymentRecipientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentRecipientServiceServer will
// result in compilation errors.
type UnsafePaymentRecipientServiceServer interface {
	mustEmbedUnimplementedPaymentRecipientServiceServer()
}

func RegisterPaymentRecipientServiceServer(s grpc.ServiceRegistrar, srv PaymentRecipientServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentRecipientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentRecipientService_ServiceDesc, srv)
}

func _PaymentRecipientService_GetPaymentRecipients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRecipientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentRecipientServiceServer).GetPaymentRecipients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentRecipientService_GetPaymentRecipients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentRecipientServiceServer).GetPaymentRecipients(ctx, req.(*GetPaymentRecipientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentRecipientService_CreatePaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentRecipientServiceServer).CreatePaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentRecipientService_CreatePaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentRecipientServiceServer).CreatePaymentRecipient(ctx, req.(*CreatePaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentRecipientService_UpdatePaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentRecipientServiceServer).UpdatePaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentRecipientService_UpdatePaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentRecipientServiceServer).UpdatePaymentRecipient(ctx, req.(*UpdatePaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentRecipientService_DeletePaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentRecipientServiceServer).DeletePaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentRecipientService_DeletePaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentRecipientServiceServer).DeletePaymentRecipient(ctx, req.(*DeletePaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentRecipientService_ServiceDesc is the grpc.ServiceDesc for PaymentRecipientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentRecipientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bank.PaymentRecipientService",
	HandlerType: (*PaymentRecipientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPaymentRecipients",
			Handler:    _PaymentRecipientService_GetPaymentRecipients_Handler,
		},
		{
			MethodName: "CreatePaymentRecipient",
			Handler:    _PaymentRecipientService_CreatePaymentRecipient_Handler,
		},
		{
			MethodName: "UpdatePaymentRecipient",
			Handler:    _PaymentRecipientService_UpdatePaymentRecipient_Handler,
		},
		{
			MethodName: "DeletePaymentRecipient",
			Handler:    _PaymentRecipientService_DeletePaymentRecipient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank/recipient.proto",
}
