// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: bank/transaction.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common fields:
	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // da li je transfer ili placanje
	// Note: PK == id + type, jer transfer i placanje mogu imati iste id-jeve
	FromAccount   string `protobuf:"bytes,3,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     string `protobuf:"bytes,4,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	InitialAmount int64  `protobuf:"varint,5,opt,name=initial_amount,json=initialAmount,proto3" json:"initial_amount,omitempty"`
	FinalAmount   int64  `protobuf:"varint,6,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	Fee           int64  `protobuf:"varint,7,opt,name=fee,proto3" json:"fee,omitempty"`
	Currency      string `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     string `protobuf:"bytes,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Payment specific;
	PaymentCode     string `protobuf:"bytes,9,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	ReferenceNumber string `protobuf:"bytes,10,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Purpose         string `protobuf:"bytes,11,opt,name=purpose,proto3" json:"purpose,omitempty"`
	RecipientId     int64  `protobuf:"varint,14,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	// Transfer specific;
	StartCurrencyId  int64   `protobuf:"varint,15,opt,name=start_currency_id,json=startCurrencyId,proto3" json:"start_currency_id,omitempty"`
	TargetCurrencyId int64   `protobuf:"varint,17,opt,name=target_currency_id,json=targetCurrencyId,proto3" json:"target_currency_id,omitempty"`
	ExchangeRate     float64 `protobuf:"fixed64,16,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_bank_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *Transaction) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *Transaction) GetInitialAmount() int64 {
	if x != nil {
		return x.InitialAmount
	}
	return 0
}

func (x *Transaction) GetFinalAmount() int64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *Transaction) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Transaction) GetPaymentCode() string {
	if x != nil {
		return x.PaymentCode
	}
	return ""
}

func (x *Transaction) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *Transaction) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *Transaction) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *Transaction) GetStartCurrencyId() int64 {
	if x != nil {
		return x.StartCurrencyId
	}
	return 0
}

func (x *Transaction) GetTargetCurrencyId() int64 {
	if x != nil {
		return x.TargetCurrencyId
	}
	return 0
}

func (x *Transaction) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	DateFrom      string                 `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	AmountFrom    int64                  `protobuf:"varint,4,opt,name=amount_from,json=amountFrom,proto3" json:"amount_from,omitempty"`
	AmountTo      int64                  `protobuf:"varint,5,opt,name=amount_to,json=amountTo,proto3" json:"amount_to,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,9,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,10,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_bank_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionsRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *GetTransactionsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetTransactionsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *GetTransactionsRequest) GetAmountFrom() int64 {
	if x != nil {
		return x.AmountFrom
	}
	return 0
}

func (x *GetTransactionsRequest) GetAmountTo() int64 {
	if x != nil {
		return x.AmountTo
	}
	return 0
}

func (x *GetTransactionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTransactionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTransactionsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetTransactionsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_bank_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransactionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTransactionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTransactionsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetTransactionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionByIdRequest) Reset() {
	*x = GetTransactionByIdRequest{}
	mi := &file_bank_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByIdRequest) ProtoMessage() {}

func (x *GetTransactionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionByIdRequest) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTransactionByIdRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetTransactionByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionByIdResponse) Reset() {
	*x = GetTransactionByIdResponse{}
	mi := &file_bank_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByIdResponse) ProtoMessage() {}

func (x *GetTransactionByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionByIdResponse) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionByIdResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GenerateTransactionPdfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTransactionPdfRequest) Reset() {
	*x = GenerateTransactionPdfRequest{}
	mi := &file_bank_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTransactionPdfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTransactionPdfRequest) ProtoMessage() {}

func (x *GenerateTransactionPdfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTransactionPdfRequest.ProtoReflect.Descriptor instead.
func (*GenerateTransactionPdfRequest) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateTransactionPdfRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GenerateTransactionPdfRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GenerateTransactionPdfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pdf           []byte                 `protobuf:"bytes,1,opt,name=pdf,proto3" json:"pdf,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTransactionPdfResponse) Reset() {
	*x = GenerateTransactionPdfResponse{}
	mi := &file_bank_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTransactionPdfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTransactionPdfResponse) ProtoMessage() {}

func (x *GenerateTransactionPdfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTransactionPdfResponse.ProtoReflect.Descriptor instead.
func (*GenerateTransactionPdfResponse) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateTransactionPdfResponse) GetPdf() []byte {
	if x != nil {
		return x.Pdf
	}
	return nil
}

func (x *GenerateTransactionPdfResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type PaymentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SenderAccount    string                 `protobuf:"bytes,1,opt,name=sender_account,json=senderAccount,proto3" json:"sender_account,omitempty"`
	RecipientAccount string                 `protobuf:"bytes,2,opt,name=recipient_account,json=recipientAccount,proto3" json:"recipient_account,omitempty"`
	RecipientName    string                 `protobuf:"bytes,3,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	Amount           int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentCode      int64                  `protobuf:"varint,5,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	ReferenceNumber  string                 `protobuf:"bytes,6,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Purpose          string                 `protobuf:"bytes,7,opt,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_bank_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentRequest) GetSenderAccount() string {
	if x != nil {
		return x.SenderAccount
	}
	return ""
}

func (x *PaymentRequest) GetRecipientAccount() string {
	if x != nil {
		return x.RecipientAccount
	}
	return ""
}

func (x *PaymentRequest) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *PaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequest) GetPaymentCode() int64 {
	if x != nil {
		return x.PaymentCode
	}
	return 0
}

func (x *PaymentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *PaymentRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type PaymentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromAccount     string                 `protobuf:"bytes,1,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount       string                 `protobuf:"bytes,2,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	InitialAmount   int64                  `protobuf:"varint,3,opt,name=initial_amount,json=initialAmount,proto3" json:"initial_amount,omitempty"`
	FinalAmount     int64                  `protobuf:"varint,4,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	Fee             int64                  `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentCode     int64                  `protobuf:"varint,7,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,8,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Purpose         string                 `protobuf:"bytes,9,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp       string                 `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_bank_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentResponse) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *PaymentResponse) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *PaymentResponse) GetInitialAmount() int64 {
	if x != nil {
		return x.InitialAmount
	}
	return 0
}

func (x *PaymentResponse) GetFinalAmount() int64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *PaymentResponse) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *PaymentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentResponse) GetPaymentCode() int64 {
	if x != nil {
		return x.PaymentCode
	}
	return 0
}

func (x *PaymentResponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *PaymentResponse) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *PaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccount   string                 `protobuf:"bytes,1,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     string                 `protobuf:"bytes,2,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_bank_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *TransferRequest) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *TransferRequest) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *TransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TransferResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromAccount     string                 `protobuf:"bytes,1,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount       string                 `protobuf:"bytes,2,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	InitialAmount   int64                  `protobuf:"varint,3,opt,name=initial_amount,json=initialAmount,proto3" json:"initial_amount,omitempty"`
	FinalAmount     int64                  `protobuf:"varint,4,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	Fee             int64                  `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentCode     string                 `protobuf:"bytes,7,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,8,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Purpose         string                 `protobuf:"bytes,9,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp       string                 `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_bank_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *TransferResponse) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *TransferResponse) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *TransferResponse) GetInitialAmount() int64 {
	if x != nil {
		return x.InitialAmount
	}
	return 0
}

func (x *TransferResponse) GetFinalAmount() int64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *TransferResponse) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TransferResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransferResponse) GetPaymentCode() string {
	if x != nil {
		return x.PaymentCode
	}
	return ""
}

func (x *TransferResponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *TransferResponse) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *TransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type TransferHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferHistoryRequest) Reset() {
	*x = TransferHistoryRequest{}
	mi := &file_bank_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferHistoryRequest) ProtoMessage() {}

func (x *TransferHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferHistoryRequest.ProtoReflect.Descriptor instead.
func (*TransferHistoryRequest) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *TransferHistoryRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TransferHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TransferHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type TransferHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*TransferResponse    `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferHistoryResponse) Reset() {
	*x = TransferHistoryResponse{}
	mi := &file_bank_transaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferHistoryResponse) ProtoMessage() {}

func (x *TransferHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_transaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferHistoryResponse.ProtoReflect.Descriptor instead.
func (*TransferHistoryResponse) Descriptor() ([]byte, []int) {
	return file_bank_transaction_proto_rawDescGZIP(), []int{12}
}

func (x *TransferHistoryResponse) GetHistory() []*TransferResponse {
	if x != nil {
		return x.History
	}
	return nil
}

var File_bank_transaction_proto protoreflect.FileDescriptor

const file_bank_transaction_proto_rawDesc = "" +
	"\n" +
	"\x16bank/transaction.proto\x12\x04bank\"\xab\x04\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\ffrom_account\x18\x03 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x04 \x01(\tR\ttoAccount\x12%\n" +
	"\x0einitial_amount\x18\x05 \x01(\x03R\rinitialAmount\x12!\n" +
	"\ffinal_amount\x18\x06 \x01(\x03R\vfinalAmount\x12\x10\n" +
	"\x03fee\x18\a \x01(\x03R\x03fee\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\r \x01(\tR\ttimestamp\x12!\n" +
	"\fpayment_code\x18\t \x01(\tR\vpaymentCode\x12)\n" +
	"\x10reference_number\x18\n" +
	" \x01(\tR\x0freferenceNumber\x12\x18\n" +
	"\apurpose\x18\v \x01(\tR\apurpose\x12!\n" +
	"\frecipient_id\x18\x0e \x01(\x03R\vrecipientId\x12*\n" +
	"\x11start_currency_id\x18\x0f \x01(\x03R\x0fstartCurrencyId\x12,\n" +
	"\x12target_currency_id\x18\x11 \x01(\x03R\x10targetCurrencyId\x12#\n" +
	"\rexchange_rate\x18\x10 \x01(\x01R\fexchangeRate\"\xb4\x02\n" +
	"\x16GetTransactionsRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x1b\n" +
	"\tdate_from\x18\x02 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x03 \x01(\tR\x06dateTo\x12\x1f\n" +
	"\vamount_from\x18\x04 \x01(\x03R\n" +
	"amountFrom\x12\x1b\n" +
	"\tamount_to\x18\x05 \x01(\x03R\bamountTo\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\a \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\b \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\t \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\n" +
	" \x01(\tR\tsortOrder\"\xb8\x01\n" +
	"\x17GetTransactionsResponse\x125\n" +
	"\ftransactions\x18\x01 \x03(\v2\x11.bank.TransactionR\ftransactions\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"?\n" +
	"\x19GetTransactionByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"Q\n" +
	"\x1aGetTransactionByIdResponse\x123\n" +
	"\vtransaction\x18\x01 \x01(\v2\x11.bank.TransactionR\vtransaction\"C\n" +
	"\x1dGenerateTransactionPdfRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"O\n" +
	"\x1eGenerateTransactionPdfResponse\x12\x10\n" +
	"\x03pdf\x18\x01 \x01(\fR\x03pdf\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"\x8b\x02\n" +
	"\x0ePaymentRequest\x12%\n" +
	"\x0esender_account\x18\x01 \x01(\tR\rsenderAccount\x12+\n" +
	"\x11recipient_account\x18\x02 \x01(\tR\x10recipientAccount\x12%\n" +
	"\x0erecipient_name\x18\x03 \x01(\tR\rrecipientName\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12!\n" +
	"\fpayment_code\x18\x05 \x01(\x03R\vpaymentCode\x12)\n" +
	"\x10reference_number\x18\x06 \x01(\tR\x0freferenceNumber\x12\x18\n" +
	"\apurpose\x18\a \x01(\tR\apurpose\"\xe9\x02\n" +
	"\x0fPaymentResponse\x12!\n" +
	"\ffrom_account\x18\x01 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x02 \x01(\tR\ttoAccount\x12%\n" +
	"\x0einitial_amount\x18\x03 \x01(\x03R\rinitialAmount\x12!\n" +
	"\ffinal_amount\x18\x04 \x01(\x03R\vfinalAmount\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x03R\x03fee\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12!\n" +
	"\fpayment_code\x18\a \x01(\x03R\vpaymentCode\x12)\n" +
	"\x10reference_number\x18\b \x01(\tR\x0freferenceNumber\x12\x18\n" +
	"\apurpose\x18\t \x01(\tR\apurpose\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\tR\ttimestamp\"\x8d\x01\n" +
	"\x0fTransferRequest\x12!\n" +
	"\ffrom_account\x18\x01 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x02 \x01(\tR\ttoAccount\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xea\x02\n" +
	"\x10TransferResponse\x12!\n" +
	"\ffrom_account\x18\x01 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x02 \x01(\tR\ttoAccount\x12%\n" +
	"\x0einitial_amount\x18\x03 \x01(\x03R\rinitialAmount\x12!\n" +
	"\ffinal_amount\x18\x04 \x01(\x03R\vfinalAmount\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x03R\x03fee\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12!\n" +
	"\fpayment_code\x18\a \x01(\tR\vpaymentCode\x12)\n" +
	"\x10reference_number\x18\b \x01(\tR\x0freferenceNumber\x12\x18\n" +
	"\apurpose\x18\t \x01(\tR\apurpose\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\tR\ttimestamp\"_\n" +
	"\x16TransferHistoryRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"K\n" +
	"\x17TransferHistoryResponse\x120\n" +
	"\ahistory\x18\x01 \x03(\v2\x16.bank.TransferResponseR\ahistoryB7Z5github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/bankb\x06proto3"

var (
	file_bank_transaction_proto_rawDescOnce sync.Once
	file_bank_transaction_proto_rawDescData []byte
)

func file_bank_transaction_proto_rawDescGZIP() []byte {
	file_bank_transaction_proto_rawDescOnce.Do(func() {
		file_bank_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bank_transaction_proto_rawDesc), len(file_bank_transaction_proto_rawDesc)))
	})
	return file_bank_transaction_proto_rawDescData
}

var file_bank_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_bank_transaction_proto_goTypes = []any{
	(*Transaction)(nil),                    // 0: bank.Transaction
	(*GetTransactionsRequest)(nil),         // 1: bank.GetTransactionsRequest
	(*GetTransactionsResponse)(nil),        // 2: bank.GetTransactionsResponse
	(*GetTransactionByIdRequest)(nil),      // 3: bank.GetTransactionByIdRequest
	(*GetTransactionByIdResponse)(nil),     // 4: bank.GetTransactionByIdResponse
	(*GenerateTransactionPdfRequest)(nil),  // 5: bank.GenerateTransactionPdfRequest
	(*GenerateTransactionPdfResponse)(nil), // 6: bank.GenerateTransactionPdfResponse
	(*PaymentRequest)(nil),                 // 7: bank.PaymentRequest
	(*PaymentResponse)(nil),                // 8: bank.PaymentResponse
	(*TransferRequest)(nil),                // 9: bank.TransferRequest
	(*TransferResponse)(nil),               // 10: bank.TransferResponse
	(*TransferHistoryRequest)(nil),         // 11: bank.TransferHistoryRequest
	(*TransferHistoryResponse)(nil),        // 12: bank.TransferHistoryResponse
}
var file_bank_transaction_proto_depIdxs = []int32{
	0,  // 0: bank.GetTransactionsResponse.transactions:type_name -> bank.Transaction
	0,  // 1: bank.GetTransactionByIdResponse.transaction:type_name -> bank.Transaction
	10, // 2: bank.TransferHistoryResponse.history:type_name -> bank.TransferResponse
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_bank_transaction_proto_init() }
func file_bank_transaction_proto_init() {
	if File_bank_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_transaction_proto_rawDesc), len(file_bank_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bank_transaction_proto_goTypes,
		DependencyIndexes: file_bank_transaction_proto_depIdxs,
		MessageInfos:      file_bank_transaction_proto_msgTypes,
	}.Build()
	File_bank_transaction_proto = out.File
	file_bank_transaction_proto_goTypes = nil
	file_bank_transaction_proto_depIdxs = nil
}
