name: gateway

on:
  pull_request:
    paths:
      - 'services/gateway/**'
      - 'pkg/**'
      - 'go.work'
      - 'go.work.sum'
      - 'docker/Dockerfile'
      - '.github/workflows/gateway.yml'
      - '.github/workflows/_service.yml'
  push:
    branches: [main]
    paths:
      - 'services/gateway/**'
      - 'pkg/**'
      - 'go.work'
      - 'go.work.sum'
      - 'docker/Dockerfile'
      - '.github/workflows/gateway.yml'
      - '.github/workflows/_service.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/_service.yml
    with:
      service: gateway
    permissions:
      contents: read
      packages: write
