name: notification

on:
  pull_request:
    paths:
      - 'services/notification/**'
      - 'pkg/**'
      - 'go.work'
      - 'go.work.sum'
      - 'docker/Dockerfile'
      - '.github/workflows/notification.yml'
      - '.github/workflows/_service.yml'
  push:
    branches: [main]
    paths:
      - 'services/notification/**'
      - 'pkg/**'
      - 'go.work'
      - 'go.work.sum'
      - 'docker/Dockerfile'
      - '.github/workflows/notification.yml'
      - '.github/workflows/_service.yml'

jobs:
  pipeline:
    uses: ./.github/workflows/_service.yml
    with:
      service: notification
    permissions:
      contents: read
      packages: write
